import assert from 'node:assert/strict';import {readFileSync,writeFileSync} from 'node:fs';import {createHash} from 'node:crypto';import {fileURLToPath} from 'node:url';import {join} from 'node:path';
import {courses,filterCourses,normal,step,lessonCount,lessonUrl,consultationUrl} from '../src/migration/catalogue';
import {emptyNotebook,parseNotebook,saveNotebook,NOTEBOOK_KEY,type Store} from '../src/migration/notebook-store';
const root=fileURLToPath(new URL('../',import.meta.url));const rows:{id:string;name:string;pass:boolean;error?:string}[]=[];
function test(name:string,fn:()=>unknown){try{fn();rows.push({id:'D'+String(rows.length+1).padStart(2,'0'),name,pass:true});}catch(e){rows.push({id:'D'+String(rows.length+1).padStart(2,'0'),name,pass:false,error:e instanceof Error?e.message:String(e)});}}
const reject=(name:string,fn:()=>unknown)=>test(name,()=>assert.throws(fn));
test('Catalogue count is 13',()=>assert.equal(courses.length,13));
test('Course slugs are unique',()=>assert.equal(new Set(courses.map(c=>c.slug)).size,13));
for(const [grade,count]of [[10,4],[11,4],[12,5]])test('Grade '+grade+' has expected source count',()=>assert.equal(filterCourses(grade,'').length,count));
test('Search normalization handles Vietnamese Đ and accents',()=>assert.equal(normal('  ĐẠO HÀM  '),'dao ham'));
test('Accentless search finds three foundation courses',()=>assert.equal(filterCourses('all','nen tang').length,3));
test('Unknown search yields no fabricated course',()=>assert.equal(filterCourses('all','xyznoresult5881').length,0));
test('Roadmap order is stable step order per grade',()=>assert.deepEqual(filterCourses(12,'').map(step),[1,2,3,4,5]));
test('Filtering does not mutate source order',()=>{const before=courses.map(c=>c.slug);filterCourses('all','','name');assert.deepEqual(courses.map(c=>c.slug),before);});
test('All source cover files exist and hashes match',()=>{const assets=JSON.parse(readFileSync(join(root,'src/migration/assets.json'),'utf8'));assert.equal(assets.length,23);for(const a of assets){const b=readFileSync(join(root,'public',a.local));assert.equal(createHash('sha256').update(b).digest('hex'),a.sha256);}});
test('No protected video links in sanitized catalogue',()=>assert.equal(/videoId|player\.mediadelivery|refreshToken|password/.test(readFileSync(join(root,'src/migration/catalog.json'),'utf8')),false));
test('Lesson count is based only on supplied chapters',()=>assert.equal(lessonCount(courses.find(c=>c.slug==='step-1-nen-tang-toan-12')!),25));
test('Lesson source URLs encode spaces and contain correct course id',()=>{const c=courses.find(c=>c.grade===12&&lessonCount(c)>0)!;const l=c.sections[0].lessons[0],url=new URL(lessonUrl(c,l));assert.equal(url.origin,'https://elearning-fe-eight.vercel.app');assert.equal(decodeURIComponent(url.pathname.slice('/bai-hoc/'.length)),l.slug);assert.equal(url.searchParams.get('courseSlug'),c.slug);});
test('Consultation carries topic without triggering send',()=>{const c=courses[0],url=new URL(consultationUrl(c),'https://www.minhthanhmath.vn');assert.equal(url.hash,'#register');assert.equal(url.searchParams.get('quan-tam'),c.title);});
test('No storage initializes genuinely empty notebook',()=>assert.deepEqual(parseNotebook(null),emptyNotebook()));
const good:Store={version:1,days:{'2026-10-06':[{id:'task-1',text:'Ôn tập',minutes:30,done:false}]},goals:{'2026-10':'Học đúng điều kiện'}};
test('Valid notebook parse preserves exact content',()=>assert.deepEqual(parseNotebook(JSON.stringify(good)),good));
reject('Malformed JSON rejected',()=>parseNotebook('{broken'));
reject('Unknown notebook version rejected',()=>parseNotebook(JSON.stringify({...good,version:2})));
reject('Unknown root metadata rejected',()=>parseNotebook(JSON.stringify({...good,serverSync:true})));
reject('Invalid date not silently dropped',()=>parseNotebook(JSON.stringify({...good,days:{'2026-02-30':[]}})));
reject('Invalid month rejected',()=>parseNotebook(JSON.stringify({...good,goals:{'2026-13':'x'}})));
reject('Negative minutes rejected',()=>parseNotebook(JSON.stringify({...good,days:{'2026-10-06':[{...good.days['2026-10-06'][0],minutes:-1}]}})));
reject('Fractional minutes rejected',()=>parseNotebook(JSON.stringify({...good,days:{'2026-10-06':[{...good.days['2026-10-06'][0],minutes:.5}]}})));
reject('More than 30 tasks rejected',()=>parseNotebook(JSON.stringify({...good,days:{'2026-10-06':Array.from({length:31},(_,i)=>({...good.days['2026-10-06'][0],id:'task-'+i}))}})));
reject('Repeated task id rejected',()=>parseNotebook(JSON.stringify({...good,days:{'2026-10-06':[good.days['2026-10-06'][0],good.days['2026-10-06'][0]]}})));
reject('Blank task text rejected',()=>parseNotebook(JSON.stringify({...good,days:{'2026-10-06':[{...good.days['2026-10-06'][0],text:' '} ]}})));
reject('Unexpected task fields rejected instead of lost on rewrite',()=>parseNotebook(JSON.stringify({...good,days:{'2026-10-06':[{...good.days['2026-10-06'][0],teacherComment:'keep me'}]}})));
reject('Wrong boolean status rejected',()=>parseNotebook(JSON.stringify({...good,days:{'2026-10-06':[{...good.days['2026-10-06'][0],done:'false'}]}})));
reject('Oversize storage rejected before parsing',()=>parseNotebook('x'.repeat(1000001)));
const map=new Map<string,string>();const storage={getItem:(k:string)=>map.get(k)??null,setItem:(k:string,v:string)=>{map.set(k,v);}};
test('Save succeeds against original expected raw value',()=>{const r=saveNotebook(storage,null,good);assert.equal(map.get(NOTEBOOK_KEY),r);assert.deepEqual(parseNotebook(r),good);});
test('Cross-tab mismatch blocks and retains other tab data',()=>{map.set(NOTEBOOK_KEY,'original-other-tab');assert.throws(()=>saveNotebook(storage,null,good));assert.equal(map.get(NOTEBOOK_KEY),'original-other-tab');});
test('Storage quota failure propagates and cannot claim save',()=>assert.throws(()=>saveNotebook({getItem:()=>null,setItem:()=>{throw new Error('QuotaExceeded');}},null,good),/QuotaExceeded/));
test('Valid day with zero tasks is preserved',()=>{const v=emptyNotebook();v.days['2026-10-07']=[];assert.deepEqual(parseNotebook(JSON.stringify(v)),v);});
test('Plain text is not evaluated by store',()=>{const v=structuredClone(good);v.days['2026-10-06'][0].text='<script>alert(1)</script>';assert.equal(parseNotebook(JSON.stringify(v)).days['2026-10-06'][0].text,'<script>alert(1)</script>');});
const passed=rows.filter(r=>r.pass).length;const report={checked_at:new Date().toISOString(),total:rows.length,passed,failed:rows.length-passed,rows,source_files:['src/migration/catalogue.ts','src/migration/notebook-store.ts'].map(rel=>({path:rel,sha256:createHash('sha256').update(readFileSync(join(root,rel))).digest('hex')})),independent_review:false,production:false};const out=process.env.MTM_TEST_REPORT||join(root,'tests/CORE_REPORT.json');writeFileSync(out,JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({total:rows.length,passed,failed:rows.length-passed,failures:rows.filter(r=>!r.pass),lessonCount: courses.reduce((s,c)=>s+lessonCount(c),0)}));process.exitCode=report.failed?1:0;
