import assert from 'node:assert/strict';
import {writeFileSync} from 'node:fs';
import {planNotebookImport,applyNotebookImport} from '../src/migration/notebook-restore';
import {NOTEBOOK_KEY,emptyNotebook,parseNotebook,type Store} from '../src/migration/notebook-store';
const task=(id:string,text='Việc kiểm thử')=>({id,text,minutes:30,done:false});
const current:Store={version:1,days:{'2026-10-06':[task('existing')]},goals:{'2026-10':'Giữ mục tiêu này'}};
const incoming:Store={version:1,days:{'2026-10-07':[task('new','Việc mới')], '2026-10-06':[task('existing')]},goals:{'2026-11':'Mục tiêu mới','2026-10':'Giữ mục tiêu này'}};
const rows:{name:string;pass:boolean;error?:string}[]=[];
function test(name:string,fn:()=>void){try{fn();rows.push({name,pass:true});}catch(e){rows.push({name,pass:false,error:e instanceof Error?e.message:String(e)});}}
const raw=JSON.stringify(current),importRaw=JSON.stringify(incoming),plan=planNotebookImport(current,importRaw);
test('Merge preview counts genuine additions only',()=>assert.deepEqual([plan.addedTasks,plan.addedGoals,plan.duplicates],[1,1,2]));
test('Existing day and goal are preserved byte-equivalent in memory',()=>{assert.deepEqual(plan.next!.days['2026-10-06'],current.days['2026-10-06']);assert.equal(plan.next!.goals['2026-10'],current.goals['2026-10']);});
test('Preview does not mutate current state',()=>assert.equal(JSON.stringify(current),raw));
test('Preview does not mutate incoming state',()=>assert.equal(JSON.stringify(incoming),importRaw));
test('Imported record objects are copied, not aliased',()=>{const p=planNotebookImport(current,importRaw);p.next!.days['2026-10-06'][0].done=true;assert.equal(current.days['2026-10-06'][0].done,false);});
test('Same id with changed content blocks entire import',()=>{const p=planNotebookImport(current,JSON.stringify({...incoming,days:{'2026-10-06':[task('existing','Changed')],'2026-10-07':[task('new')]}}));assert.equal(p.next,null);assert.equal(p.conflicts[0].kind,'task');});
test('Same id changed completion is a conflict, not a silent overwrite',()=>assert.equal(planNotebookImport(current,JSON.stringify({version:1,days:{'2026-10-06':[{...task('existing'),done:true}]},goals:{}})).next,null));
test('Same month changed goal blocks entire import',()=>{const p=planNotebookImport(current,JSON.stringify({...incoming,goals:{'2026-10':'Changed'}}));assert.equal(p.next,null);assert.equal(p.conflicts[0].kind,'goal');});
test('Merge cannot exceed 30 tasks per day',()=>assert.throws(()=>planNotebookImport({version:1,days:{'2026-10-06':Array.from({length:30},(_,i)=>task('T'+i))},goals:{}},JSON.stringify({version:1,days:{'2026-10-06':[task('extra')]},goals:{}})),/30/));
test('Invalid JSON is rejected before any write',()=>assert.throws(()=>planNotebookImport(current,'{broken')));
test('Oversize text rejected',()=>assert.throws(()=>planNotebookImport(current,' '.repeat(1000001))));
test('Unsupported version rejected',()=>assert.throws(()=>planNotebookImport(current,JSON.stringify({...incoming,version:2}))));
test('Invalid calendar date rejected',()=>assert.throws(()=>planNotebookImport(current,JSON.stringify({version:1,days:{'2026-02-30':[task('x')]},goals:{}}))));
test('Unknown root data is not silently discarded',()=>assert.throws(()=>planNotebookImport(current,JSON.stringify({...incoming,students:[]}))));
test('Duplicate ids in incoming day rejected',()=>assert.throws(()=>planNotebookImport(current,JSON.stringify({version:1,days:{'2026-10-07':[task('x'),task('x')]},goals:{}}))));
let stored=raw,writes=0;const storage={getItem(key:string){assert.equal(key,NOTEBOOK_KEY);return stored;},setItem(key:string,value:string){assert.equal(key,NOTEBOOK_KEY);stored=value;writes++;}};
test('Confirmation commits exactly one validated write',()=>{const result=applyNotebookImport(storage,raw,plan);assert.equal(result,stored);assert.equal(writes,1);assert.equal(parseNotebook(stored).days['2026-10-07'][0].id,'new');});
test('Changed storage after preview is not overwritten',()=>{const before=stored;assert.throws(()=>applyNotebookImport(storage,raw,plan),/thẻ khác/);assert.equal(stored,before);assert.equal(writes,1);});
test('Conflict plan cannot be applied',()=>{const p=planNotebookImport(current,JSON.stringify({version:1,days:{},goals:{'2026-10':'Conflict'}}));assert.throws(()=>applyNotebookImport(storage,stored,p));assert.equal(writes,1);});
test('Reimport is idempotent',()=>{const again=planNotebookImport(parseNotebook(stored),importRaw);assert.equal(again.addedTasks,0);assert.equal(again.addedGoals,0);assert.deepEqual(again.next,parseNotebook(stored));});
test('Storage quota failure is reported without claiming success',()=>assert.throws(()=>applyNotebookImport({getItem:()=>raw,setItem:()=>{throw new Error('QUOTA');}},raw,plan),/QUOTA/));
test('Empty notebook can restore a valid backup',()=>assert.deepEqual(planNotebookImport(emptyNotebook(),raw).next,current));
test('Literal HTML-like text remains data',()=>{const p=planNotebookImport(emptyNotebook(),JSON.stringify({version:1,days:{'2026-10-06':[task('html','<script>no execution</script>')]},goals:{}}));assert.equal(p.next!.days['2026-10-06'][0].text,'<script>no execution</script>');});
const failed=rows.filter(r=>!r.pass);const report={checked_at:new Date().toISOString(),scope:'PURE_NOTEBOOK_RESTORE_SYNTHETIC_DATA',total:rows.length,passed:rows.length-failed.length,failed:failed.length,rows};
if(process.env.MTM_TEST_REPORT)writeFileSync(process.env.MTM_TEST_REPORT,JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({total:report.total,passed:report.passed,failed:report.failed,failures:failed}));process.exitCode=failed.length?1:0;
