import assert from 'node:assert/strict';import {writeFileSync} from 'node:fs';
import {parseCatalogQuery,catalogURL,routeMetadata,normalizePublicPath,PUBLIC_PATHS} from '../src/migration/route-policy';import {courses,filterCourses} from '../src/migration/catalogue';
const rows:{name:string;pass:boolean;error?:string}[]=[];const test=(name:string,f:()=>void)=>{try{f();rows.push({name,pass:true});}catch(e){rows.push({name,pass:false,error:e instanceof Error?e.message:String(e)});}};
test('Default catalogue state is explicit',()=>assert.deepEqual(parseCatalogQuery(''),{grade:'12',query:'',order:'roadmap'}));
test('Reloaded class, search and sorting read from one URL',()=>assert.deepEqual(parseCatalogQuery('?lop=11&q=nen+tang&sort=name'),{grade:'11',query:'nen tang',order:'name'}));
test('Invalid filter values fall back without inventing data',()=>assert.deepEqual(parseCatalogQuery('?lop=999&sort=price'),{grade:'12',query:'',order:'roadmap'}));
test('Search payload is bounded from manually edited URLs',()=>assert.equal(parseCatalogQuery('?q='+'a'.repeat(1000)).query.length,120));
test('Control characters are removed from query display',()=>assert.equal(parseCatalogQuery('?q=a%00%0Ab').query,'ab'));
test('Encoded Vietnamese values survive URL serialization',()=>{const s={grade:'all',query:'Hàm số & đồ thị',order:'name'}as const;assert.deepEqual(parseCatalogQuery(catalogURL(s).split('?')[1]),s);});
test('Clearing query removes stale q parameter',()=>assert.equal(new URL(catalogURL({grade:'10',query:'',order:'name'}),'https://mtm.invalid').searchParams.has('q'),false));
test('Default sorting produces no redundant sort parameter',()=>assert.ok(!catalogURL({grade:'12',query:'',order:'roadmap'}).includes('sort=')));
test('Class/search/sort state is reproducible in actual filtering',()=>{const s=parseCatalogQuery('?lop=all&q=nen+tang&sort=name');assert.equal(filterCourses(s.grade,s.query,s.order).length,3);});
test('All 13 course detail routes resolve unique canonical and original image',()=>{const seen=new Set();for(const c of courses){const m=routeMetadata('/khoa-hoc/'+c.slug,'www.minhthanhmath.vn');assert.ok(m.known);assert.ok(m.title.includes(c.title));assert.ok(m.description.includes(c.sections.length+' chương'));assert.ok(m.ogImage.endsWith(c.image));seen.add(m.url);}assert.equal(seen.size,13);});
test('All public routes are mapped and have descriptions',()=>{for(const p of PUBLIC_PATHS){const m=routeMetadata(p,'www.minhthanhmath.vn');assert.ok(m.known);assert.ok(m.description.length>30);}});
test('Notebook is not indexed as public account content',()=>assert.equal(routeMetadata('/so-tay','www.minhthanhmath.vn').robots,'noindex, follow'));
test('Unknown path is not indexed or canonicalized as a real course',()=>{const m=routeMetadata('/khoa-hoc/unknown','www.minhthanhmath.vn');assert.equal(m.known,false);assert.equal(m.robots,'noindex, follow');assert.equal(m.url,'https://www.minhthanhmath.vn/404');});
test('Filtered search results are not separate index targets',()=>{const m=routeMetadata('/khoa-hoc','www.minhthanhmath.vn','?q=ham');assert.equal(m.robots,'noindex, follow');assert.ok(!m.url.includes('?'));});
test('Staging and localhost origins default to noindex',()=>{for(const h of ['127.0.0.1','localhost','preview.vercel.app','www.minhthanhmath.vn.evil.invalid'])assert.equal(routeMetadata('/khoa-hoc',h).robots,'noindex, follow');});
test('Official known catalogue allows indexing only on production host',()=>assert.equal(routeMetadata('/khoa-hoc','minhthanhmath.vn').robots,'index, follow'));
test('Trailing slash normalizes to the same public route',()=>assert.equal(normalizePublicPath('/khoa-hoc/'),'/khoa-hoc'));
test('Backslashes and scheme strings are not resolved as paths',()=>{assert.equal(normalizePublicPath('javascript:alert(1)'),'/not-found');assert.equal(normalizePublicPath('/a\\b'),'/not-found');});
test('Descriptions differ across catalogue, library and notebook',()=>assert.equal(new Set(['/khoa-hoc','/tai-lieu','/so-tay'].map(p=>routeMetadata(p,'www.minhthanhmath.vn').description)).size,3));
const failed=rows.filter(x=>!x.pass),report={checked_at:new Date().toISOString(),scope:'UNIFIED_FRONTEND_ROUTE_METADATA_AND_FILTER_CONTRACTS',total:rows.length,passed:rows.length-failed.length,failed:failed.length,rows};if(process.env.MTM_TEST_REPORT)writeFileSync(process.env.MTM_TEST_REPORT,JSON.stringify(report,null,2));console.log(JSON.stringify({total:report.total,passed:report.passed,failed:report.failed,failures:failed}));process.exitCode=failed.length?1:0;
