import {lazy,Suspense,useEffect,useRef} from 'react';import {BookOpen,ClipboardList,History,GraduationCap,ArrowLeft} from 'lucide-react';
import {Link,navigate} from '../migration/navigation';import {publicSnapshot,nativePathForDocument,nativePathForExam} from './model';import {Pending} from './NativeCourses';
import {normal} from '../migration/catalogue';
const ReferenceLibrary=lazy(()=>import('../components/MtmReferenceLibrary'));
const NativePdfReader=lazy(()=>import('./NativePdfReader'));
import readerFiles from './reader-files.json';
type SourceExam=(typeof publicSnapshot.exams)[number];type SourceDocument=(typeof publicSnapshot.documents)[number];
function isExam(value:SourceExam|SourceDocument):value is SourceExam{return 'duration'in value&&typeof value.duration==='number'&&'questionsCount'in value&&typeof value.questionsCount==='number';}

export default function NativeResources({kind,pathname,search}:{kind:'exams'|'documents';pathname:string;search:string}){
 const exam=kind==='exams',base=exam?'/thi-thu':'/tai-lieu',params=new URLSearchParams(search),menu=params.get('muc')??(exam?'exam':'all');
 const query=(params.get('q')??'').normalize('NFC').replace(/\s+/g,' ').replace(/[\u0000-\u001f\u007f]/g,'').slice(0,120),term=normal(query);
 const referenceDetails=useRef<HTMLDetailsElement>(null),searchInput=useRef<HTMLInputElement>(null),hash=location.hash;
 useEffect(()=>{if(!exam&&hash==='#tai-lieu-tham-khao'&&referenceDetails.current)referenceDetails.current.open=true;},[exam,pathname,hash]);
 const menus=exam?[['exam','Phòng Thi Online'],['homework','Bài Tập Về Nhà'],['history','Lịch Sử Làm Bài'],['grade-12','Đề thi Lớp 12'],['grade-11','Đề thi Lớp 11'],['grade-10','Đề thi Lớp 10']]:[['all','Tất cả tài liệu'],['grade-12','Tài liệu Lớp 12'],['grade-11','Tài liệu Lớp 11'],['grade-10','Tài liệu Lớp 10']];
 const queryString=(category:string|null,value=query)=>{const next=new URLSearchParams();if(category!==null)next.set('muc',category);const q=value.normalize('NFC').replace(/\s+/g,' ').replace(/[\u0000-\u001f\u007f]/g,'').slice(0,120);if(q.trim())next.set('q',q);return next.size?'?'+next.toString():'';};
 const selected=menus.find(x=>x[0]===menu)??menus[0],selectedSearch=queryString(selected[0]),returnUrl=base+queryString(params.has('muc')?selected[0]:null),grade=selected[0].startsWith('grade-')?Number(selected[0].slice(6)):null;
 const changeQuery=(value:string)=>navigate(base+queryString(selected[0],value),{replace:true});
 const raw=exam?publicSnapshot.exams:publicSnapshot.documents;const rows=raw.filter(x=>grade?x.grade===grade:!exam||selected[0]==='exam'?(exam?('type'in x&&x.type==='exam'):true):selected[0]==='homework'&&'type'in x&&x.type==='homework').filter(x=>!term||normal(x.title+' '+(x.description??'')).replace(/\s+/g,' ').includes(term));
 const detailId=pathname.startsWith(base+'/')?pathname.slice(base.length+1):null,detail=detailId?raw.find(x=>x.id===detailId):null;
 const pdfFile=!exam&&detail?readerFiles.files.find(x=>x.id===detail.id):undefined;
 return <div className="native-ui ne-resource-layout"><aside className="ne-resource-nav"><div className="ne-user"><span>S</span><div><b>Bản xem cục bộ</b><small>CHƯA ĐĂNG NHẬP</small></div></div><nav aria-label={exam?'Phân loại đề':'Phân loại tài liệu'}>{menus.map(([value,label],i)=><button key={value} aria-pressed={selected[0]===value} onClick={()=>navigate(base+queryString(value))}>{i===2&&exam?<History size={18}/>:exam?<ClipboardList size={18}/>:<BookOpen size={18}/>} {label}</button>)}</nav><Link className="ne-back-home" href="/"><ArrowLeft size={16}/> Về Trang Chủ</Link></aside>
 <section className="ne-resource-content"><select className="ne-mobile-select" aria-label="Chọn mục" value={selected[0]} onChange={e=>navigate(base+queryString(e.target.value))}>{menus.map(([v,label])=><option key={v} value={v}>{label}</option>)}</select><nav className="ne-resource-crumb" aria-label="Đường dẫn" style={{margin:'0 0 14px'}}>{detailId?<><Link href={returnUrl}>{exam?'Thi thử':'Tài liệu'}</Link><span aria-hidden="true"> · </span><span aria-current="page">{selected[1]}</span></>:<span aria-current="page">{exam?'Thi thử':'Tài liệu'}</span>}</nav>
 {detailId?<>{detail?<><h1>{detail.title}</h1><article className="ne-white ne-padding"><p>{detail.description||'Không có mô tả chi tiết từ giáo viên.'}</p>{isExam(detail)&&<p>Thời gian theo nguồn: {detail.duration} phút · {detail.questionsCount} câu hỏi</p>}{pdfFile?<Suspense fallback={<p role="status">Đang mở trình đọc PDF…</p>}><NativePdfReader key={pdfFile.id} file={pdfFile} title={detail.title} search={search}/></Suspense>:<><Pending>{exam?'Trang đề đã có địa chỉ nội bộ. Nội dung đề, lưu bài, chấm điểm và lịch sử chưa được tích hợp nên chưa thể bắt đầu bài thi.':'Tệp này chưa có bản nguồn đã kiểm. Chưa mở tài liệu.'}</Pending><button disabled>{exam?'Bắt đầu làm bài':'Đọc tài liệu'}</button></>}<p><Link href={returnUrl}>Trở lại danh sách</Link></p></article></>:<article className="ne-white ne-padding"><h1>Không tìm thấy {exam?'đề thi':'tài liệu'}</h1><Link href={returnUrl}>Về danh sách</Link></article>}</>:<><h1>{selected[1]}</h1>{selected[0]==='history'?<div className="ne-white ne-padding"><Pending>Lịch sử theo tài khoản chưa được kết nối. Chưa có dữ liệu kết quả để hiển thị ở bản này.</Pending></div>:<><div className="ne-search-row"><input ref={searchInput} type="search" aria-label="Tìm học liệu" placeholder="Tên hoặc mô tả học liệu…" maxLength={120} value={query} onChange={e=>changeQuery(e.target.value)}/><button type="button" aria-label="Xóa tìm kiếm học liệu" onClick={()=>{changeQuery('');searchInput.current?.focus();}}>Xóa tìm kiếm</button></div><p className="ne-resource-count" role="status" aria-live="polite" aria-atomic="true">{exam?'Danh sách học liệu sẵn có':'Học liệu thư viện hiện tại'} ({rows.length})</p><div className="ne-resource-grid">{rows.map(x=><article className="ne-resource-card" key={x.id}><div className="ne-resource-labels"><span>Lớp {x.grade}</span>{exam&&<small>{'type'in x&&x.type==='homework'?'Bài tập':'Đề thi'}</small>}</div><h2>{x.title}</h2><p>{x.description||'Không có mô tả chi tiết từ giáo viên.'}</p>{isExam(x)?<div className="ne-resource-facts"><span>Thời gian: {x.duration} phút</span><span>{x.questionsCount} câu hỏi</span></div>:<p>Ngày đăng: {new Date(x.createdAt).toLocaleDateString('vi-VN')}</p>}<Link className="ne-primary" href={(exam?nativePathForExam(x.id):nativePathForDocument(x.id))+selectedSearch}>{exam?'Bắt đầu làm bài':'Đọc tài liệu →'}</Link></article>)}</div>{!rows.length&&<p className="ne-empty">{term?'Không tìm thấy học liệu phù hợp':'Chưa có học liệu trong mục này ở nguồn đã đối chiếu.'}</p>}</>}
 <Pending>{exam?'Danh sách theo nguồn công khai. Trình làm bài và tài khoản chưa tích hợp; không chuyển sang E-learning cũ.':'Tài liệu công khai được đọc ngay tại MTM. Nguồn hiện có 5 mục dùng chung 2 tệp PDF; một số nhãn/lớp chưa khớp bìa và cần chuẩn hóa trước khi phát hành. Không tự sửa nội dung hoặc thay tệp nguồn.'}</Pending>
 {!exam&&<details ref={referenceDetails} className="ne-reference-more" id="ne-reference-details"><summary>Kho tham khảo MTM hiện có — 1.200 mục</summary><Suspense fallback={<p>Đang tải kho tham khảo…</p>}><ReferenceLibrary/></Suspense></details>}</>}
 </section></div>;
}
