import {createElement,useMemo,useRef,useState,type ReactNode} from 'react';
import {Search,ChevronDown,LockKeyhole,ArrowLeft,ArrowRight,BookOpen,MessageCircle} from 'lucide-react';
import {Link,navigate} from '../migration/navigation';
import {courses,filterCourses,lessonCount,type Course} from '../migration/catalogue';
import {parseCatalogQuery,catalogURL} from '../migration/route-policy';
import {nativeCourseMetadata,nativeLessonUrl,resolveNativeLesson,publicSnapshot} from './model';
import {courseSearch} from './course-search';
import './native.css';
const money=(value:number|null|undefined)=>value==null?'Chờ xác nhận':new Intl.NumberFormat('vi-VN').format(value)+' VNĐ';
export function Pending({children}:{children:ReactNode}){return <p className="ne-pending" role="status">{children}</p>;}
export function SnapshotNotice(){return <div className="ne-snapshot">Nội dung và học phí theo bản chụp nguồn ngày {publicSnapshot.capturedAt.slice(0,10)}; học phí cần xác nhận, thanh toán chưa được kết nối.</div>;}
function SafeOverview({html}:{html:string}){
 const content=useMemo(()=>{const doc=new DOMParser().parseFromString(html,'text/html');let count=0;const visit=(node:Node):ReactNode=>{if(++count>2000)return null;if(node.nodeType===3)return node.textContent;if(!(node instanceof Element))return null;const tag=node.tagName.toLowerCase();if(['script','style','iframe','object','embed','form','input','img','svg'].includes(tag))return null;const children=Array.from(node.childNodes).map(visit);return ['p','h2','h3','h4','ul','ol','li','strong','b','em','i','br','blockquote','span'].includes(tag)?createElement(tag,{key:count},...children):<span key={count}>{children}</span>;};return Array.from(doc.body.childNodes).map(visit);},[html]);
 return <div className="ne-overview">{content}</div>;
}
export function NativeCatalogue({search}:{search:string}){
 const state=parseCatalogQuery(search),[advanced,setAdvanced]=useState(false);const list=filterCourses(state.grade,state.query,state.order);const year=state.grade==='12'?2026:state.grade==='11'?2027:2028;const group=state.grade==='12'?2008:state.grade==='11'?2009:2010;
 const change=(patch:Partial<typeof state>,replace=false)=>navigate(catalogURL({...state,...patch}),{replace});
 return <div className="native-ui"><SnapshotNotice/><section className="ne-catalog"><div className="ne-grades" aria-label="Chọn lớp">{['10','11','12'].map(grade=><button key={grade} aria-pressed={state.grade===grade} onClick={()=>change({grade:grade as typeof state.grade})}>Lớp {grade}</button>)}</div><h1 className="ne-roadmap-title">{state.grade==='all'?'Danh mục khóa học Toán':<>Lộ trình luyện thi {year} <span>dành cho {group}</span></>}</h1>
 <div className="ne-filter-toggle"><button onClick={()=>setAdvanced(!advanced)} aria-expanded={advanced}><Search size={15}/> Tìm và lọc khóa học</button></div>{(advanced||state.query||state.grade==='all')&&<div className="ne-search-row"><input aria-label="Tìm khóa học" placeholder="Tên khóa học hoặc chủ đề…" maxLength={120} value={state.query} onChange={e=>change({query:e.target.value},true)}/><select aria-label="Sắp xếp khóa học" value={state.order} onChange={e=>change({order:e.target.value as typeof state.order})}><option value="roadmap">Theo lộ trình</option><option value="name">Theo tên</option></select><button onClick={()=>change({grade:'all',query:''})}>Tất cả</button></div>}
 {list.length?<div className="ne-course-grid">{list.map(c=>{const raw=nativeCourseMetadata(c);return <article key={c.slug} className="ne-course-card"><Link href={'/khoa-hoc/'+c.slug}><img src={c.image} alt={c.title} width={1012} height={566} loading="lazy"/><h2>{c.title}</h2></Link><p>{raw?.overview||''}</p><div className="ne-price">{money(raw?.price)}</div></article>;})}</div>:<div className="ne-empty"><h2>Không tìm thấy khóa học</h2><button onClick={()=>change({query:'',grade:'all'})}>Xóa bộ lọc</button></div>}
 </section></div>;
}
export function NativeCourseDetail({course:c}:{course:Course}){
 const raw=nativeCourseMetadata(c),[tab,setTab]=useState('content'),[query,setQuery]=useState(''),[opened,setOpened]=useState(()=>new Set(c.sections.slice(0,1).map(x=>x.id)));
 const searchInput=useRef<HTMLInputElement>(null);
 const {chapters:filtered,searching,matchCount}=courseSearch(c.sections,query,opened),first=c.sections.flatMap(s=>s.lessons)[0];
 const clearSearch=()=>{setQuery('');searchInput.current?.focus();};
 return <div className="native-ui"><SnapshotNotice/><nav className="ne-breadcrumb"><Link href="/">Trang chủ</Link><span>›</span><Link href="/khoa-hoc">Danh mục khóa học</Link><span>›</span><span>{c.title}</span></nav><div className="ne-detail-grid"><div><section className="ne-white"><h1 className="ne-course-title">{c.title}</h1><div className="ne-tabs" role="tablist" aria-label="Nội dung và bình luận khóa học">{[['content','Nội dung'],['discussion','Bình luận']].map(([key,label])=><button key={key} id={'ne-tab-'+key} type="button" role="tab" aria-selected={tab===key} aria-controls={'ne-panel-'+key} tabIndex={tab===key?0:-1} onKeyDown={e=>{let next:string;if(e.key==='Home')next='content';else if(e.key==='End')next='discussion';else if(e.key==='ArrowLeft'||e.key==='ArrowRight')next=key==='content'?'discussion':'content';else return;e.preventDefault();setTab(next);requestAnimationFrame(()=>document.getElementById('ne-tab-'+next)?.focus());}} onClick={()=>setTab(key)}>{label}</button>)}</div><div id="ne-panel-content" role="tabpanel" aria-labelledby="ne-tab-content" tabIndex={0} hidden={tab!=='content'}><SafeOverview html={raw?.description||'<p>Chưa có nội dung giới thiệu trong nguồn.</p>'}/></div><div className="ne-padding" id="ne-panel-discussion" role="tabpanel" aria-labelledby="ne-tab-discussion" tabIndex={0} hidden={tab!=='discussion'}><h2>Bình luận khóa học</h2><Pending>Bình luận theo tài khoản chưa được chuyển. Chưa thể gửi hoặc đọc lịch sử; bản này không mở trang E-learning cũ thay cho chức năng.</Pending><textarea disabled aria-label="Bình luận chưa được kết nối" placeholder="Viết bình luận"/><button disabled>Gửi bình luận</button></div></section>
 <section className="ne-white ne-syllabus"><div className="ne-syllabus-title"><h2>DANH SÁCH BÀI HỌC</h2><input ref={searchInput} aria-label="Tìm kiếm bài học" placeholder="Tìm kiếm bài học…" value={query} maxLength={120} onChange={e=>setQuery(e.target.value)}/>{query.length>0&&<button type="button" aria-label="Xóa tìm kiếm bài học" onClick={clearSearch}>Xóa tìm kiếm</button>}</div>
 <div role="status" aria-atomic="true">{searching&&`${matchCount} bài học khớp tìm kiếm.`}</div>
 {filtered.map(({chapter:s,lessons,expanded})=><section className="ne-chapter" key={s.id}><h3><button aria-expanded={expanded} aria-disabled={searching||undefined} aria-controls={'ne-chapter-'+s.id} onClick={()=>{if(searching)return;setOpened(v=>{const n=new Set(v);n.has(s.id)?n.delete(s.id):n.add(s.id);return n;});}}><ChevronDown size={15} className={expanded?'':'closed'}/><span>{s.title}<small>{s.lessons.length} bài học{searching&&` · ${lessons.length} khớp tìm kiếm`}</small></span></button></h3><div hidden={!expanded} id={'ne-chapter-'+s.id}>{lessons.map(({lesson:l,ordinal})=><Link href={nativeLessonUrl(c,l)} key={l.slug} className="ne-lesson"><span className="ne-number">{String(ordinal).padStart(2,'0')}</span><span><b>{l.title}</b>{l.subtitle&&<small>{l.subtitle}</small>}</span>{l.isFree?<em>FREE</em>:<LockKeyhole size={16}/>}</Link>)}</div></section>)}{!filtered.length&&<p className="ne-empty">{c.sections.length?'Không tìm thấy bài học.':'Nguồn chưa có danh sách chương.'}</p>}</section></div>
 <aside><section className="ne-white ne-padding ne-summary"><h2>Tổng quan khóa học</h2><p><b>Học phí: {money(raw?.price)}</b></p><p><BookOpen size={15}/> <b>Cấu trúc khóa học:</b> {c.sections.map(s=>s.title).join(', ')||'Chờ cập nhật'}</p><p>{lessonCount(c)} mục bài học trong danh mục</p><button className="ne-buy" disabled aria-describedby="ne-payment-state">MUA NGAY</button><small id="ne-payment-state">Chưa nối thanh toán; nút đang khóa, không phát sinh giao dịch.</small>{first&&<Link className="ne-primary" href={nativeLessonUrl(c,first)}>Xem bài học đầu tiên <ArrowRight size={16}/></Link>}</section><section className="ne-white ne-padding"><h2>Tiện ích</h2><Link href="/tai-lieu"><BookOpen size={16}/> Tài liệu</Link><Link href="/so-tay">Sổ tay học tập</Link></section></aside></div></div>;
}
export function NativeLesson({pathname,search}:{pathname:string;search:string}){
 const model=resolveNativeLesson(pathname,search);if(!model)return <div className="native-ui ne-empty"><h1>Không tìm thấy bài học</h1><Link href="/khoa-hoc">Về danh mục khóa học</Link></div>;
 const {course,lesson,chapter,entries,index}=model;
 return <div className="native-ui"><nav className="ne-breadcrumb"><Link href="/">Trang chủ</Link><span>›</span><Link href="/khoa-hoc">Danh mục khóa học</Link><span>›</span><Link href={'/khoa-hoc/'+course.slug}>{course.title}</Link><span>›</span><span>{chapter.title}</span></nav><div className="ne-player-grid"><section className="ne-white"><div className="ne-padding"><h1 className="ne-lesson-title">{lesson.title}</h1><p>{lesson.subtitle}</p></div><div className="ne-player-pending"><LockKeyhole size={40}/><h2>Video chưa được kết nối</h2><p>Đường dẫn bài học đã ở trong website MTM. Tệp phát, kiểm quyền học và tiến độ tài khoản chưa được chuyển; chưa thể xem video tại đây.</p><span>{lesson.isFree?'Nguồn đánh dấu bài học thử; vẫn cần xác minh tệp phát thật.':'Quyền xem phải được xác thực bằng tài khoản đã đăng ký.'}</span></div><div className="ne-prev-next">{model.previous?<Link href={nativeLessonUrl(course,model.previous.lesson)}><ArrowLeft size={16}/> Bài trước</Link>:<span/>}{model.next&&<Link href={nativeLessonUrl(course,model.next.lesson)}>Bài tiếp theo <ArrowRight size={16}/></Link>}</div></section>
 <aside><section className="ne-white ne-padding"><h2 className="ne-blue">Thảo luận</h2><div className="ne-comment-disabled"><span>U</span><input disabled placeholder="Viết bình luận" aria-label="Chưa kết nối bình luận"/></div><Pending>Chưa nối dữ liệu bình luận và đăng nhập. Không hiển thị bình luận mẫu như dữ liệu thật.</Pending></section><section className="ne-white ne-padding ne-next-lessons"><h2>BÀI HỌC TRONG KHÓA</h2>{entries.map((item,n)=><Link key={item.lesson.slug} href={nativeLessonUrl(course,item.lesson)} aria-current={n===index?'page':undefined}><span>{item.lesson.isFree?<BookOpen size={15}/>:<LockKeyhole size={15}/>}</span><span>{item.lesson.title}<small>{n===index?'Đang xem thông tin bài':item.lesson.duration?'Thời lượng nguồn: '+item.lesson.duration:'Mở thông tin bài học'}</small></span></Link>)}</section></aside></div></div>;
}
