import {useEffect,useRef,useState} from 'react';
import {Link} from '../../migration/navigation';
import {SEO} from '../../components/SEO';
import {ExamEditor,type AdminActions} from '../admin/AdminExams';
import {adminRequest,requireAdmin,requireBackend,sha256,type DraftRow} from '../admin/backend';
import {newDraft,type AdminDraft} from '../admin/model';
import {LEGACY_LAYOUT} from '../admin/layout';
import ExamConfirm from '../exams/ExamConfirm';
import {date} from './types';
import type {Profile} from './types';
import './homework.css';
import '../admin/admin.css';
type ClassRow={id:string;label:string;grade:number};
type StudentRow={id:string;classId:string;profile:Profile};
type CodeRow={id:string;studentId:string;expiresAt:string;revokedAt:string|null};
type HwDraft=DraftRow&{updatedAt?:string};
type AssignmentRow={id:string;classId:string;title:string;opensAt:string;dueAt:string;visible:boolean};
async function rpc<T>(name:string,args:Record<string,unknown>,expectedOwner?:string):Promise<T>{const {user:owner,client}=await adminRequest(expectedOwner);const r=await client.rpc(name,args);if(r.error)throw Error(r.error.code==='40001'?'Bản nháp đã đổi. Tải lại trước khi giao bài.':'Chưa thực hiện được quản trị BTVN. Kiểm quyền/kết nối và thử lại.');if((await requireAdmin()).id!==owner.id)throw Error('Tài khoản đã đổi. Tải lại dữ liệu của tài khoản hiện tại.');return r.data as T;}
async function list<T>(kind:string){const r=await rpc<{items:T[]}>('mtm_hw_admin_list',{p_kind:kind,p_offset:0,p_limit:100});return r.items;}
function homeworkActions(expectedOwner?:string):AdminActions{return {
 async save(d,revision){return rpc<DraftRow>('mtm_hw_admin_save_draft',{p_id:d.id,p_revision:revision,p_payload:d},expectedOwner);},
 async upload(id,kind,file,info){const {user,client:b}=await adminRequest(expectedOwner),path=`${user.id}/${id}/${info.sha256}-${kind}.pdf`,r=await b.storage.from('mtm-homework').upload(path,file,{contentType:'application/pdf',upsert:false});if(r.error){const prior=await b.storage.from('mtm-homework').download(path);if(prior.error||!prior.data||prior.data.size!==info.bytes||await sha256(await prior.data.arrayBuffer())!==info.sha256)throw Error('Chưa tải được PDF BTVN riêng.');}if((await requireAdmin()).id!==user.id)throw Error('Tài khoản quản trị đã đổi.');return {...info,path};},
 async pdfUrl(path){const {user:owner,client}=await adminRequest(expectedOwner);const r=await client.storage.from('mtm-homework').createSignedUrl(path,300);if(r.error||!r.data)throw Error('Chưa mở được PDF riêng.');if((await requireAdmin()).id!==owner.id)throw Error('Tài khoản quản trị đã đổi.');return r.data.signedUrl;},
 async publish(){throw Error('BTVN chỉ giao theo lớp, không đăng vào danh sách đề công khai.');}
};}
function fresh():DraftRow{const d=newDraft();return {id:d.id,revision:0,updated_at:'',payload:{...d,layout:LEGACY_LAYOUT.map(s=>({...s})),pointMode:'preset',points:[...Array(12).fill(250),...Array(4).fill(1000),...Array(6).fill(500)],tfScoring:'thpt',shortMode:'numeric'}};}
export default function AdminHomework(){
 const [authorized,setAuthorized]=useState(false),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[classes,setClasses]=useState<ClassRow[]>([]),[students,setStudents]=useState<StudentRow[]>([]),[codes,setCodes]=useState<CodeRow[]>([]),[drafts,setDrafts]=useState<HwDraft[]>([]),[assignments,setAssignments]=useState<AssignmentRow[]>([]),[selected,setSelected]=useState<DraftRow|null>(null),[key,setKey]=useState(0),[ready,setReady]=useState<{draft:AdminDraft;revision:number}|null>(null),[rawCode,setRawCode]=useState(''),[codeStudent,setCodeStudent]=useState(''),[classLabel,setClassLabel]=useState(''),[grade,setGrade]=useState(10),[classId,setClassId]=useState(''),[name,setName]=useState(''),[school,setSchool]=useState(''),[schoolClass,setSchoolClass]=useState(''),[opens,setOpens]=useState(''),[due,setDue]=useState(''),[weight,setWeight]=useState(1),[ranked,setRanked]=useState(true),[confirmation,setConfirmation]=useState<{message:string;run:()=>Promise<void>}|null>(null);
 const editorOwner=useRef<string|null>(null),authGeneration=useRef(0);
 const renderOwner=editorOwner.current,renderEpoch=authGeneration.current;
 const [heldOwner,setHeldOwner]=useState<string|null>(null);
 async function ownedRpc<T>(name:string,args:Record<string,unknown>):Promise<T>{const n=authGeneration.current,id=editorOwner.current;if(!id)throw Error('Đăng nhập quản trị trước.');const out=await rpc<T>(name,args,id);if(n!==authGeneration.current||id!==editorOwner.current)throw Error('Phiên quản trị đã thay đổi.');return out;}
 const editorEpoch=authGeneration.current;
 const baseActions=homeworkActions(heldOwner??undefined);
 async function editorTask<T>(run:()=>Promise<T>):Promise<T>{if(!authorized||!heldOwner||heldOwner!==editorOwner.current||editorEpoch!==authGeneration.current)throw Error('Đăng nhập lại đúng tài khoản của bản nháp.');const out=await run();if(heldOwner!==editorOwner.current||editorEpoch!==authGeneration.current)throw Error('Phiên quản trị đã thay đổi.');return out;}
 const actions:AdminActions={save:(d,r)=>editorTask(()=>baseActions.save(d,r)),upload:(id,k,f,i)=>editorTask(()=>baseActions.upload(id,k,f,i)),publish:(d,r)=>editorTask(()=>baseActions.publish(d,r)),pdfUrl:path=>editorTask(()=>baseActions.pdfUrl(path))};
 async function refresh(){const epoch=authGeneration.current;const [c,s,k,d,a]=await Promise.all([list<ClassRow>('classes'),list<StudentRow>('students'),list<CodeRow>('codes'),list<HwDraft>('drafts'),list<AssignmentRow>('assignments')]);if(epoch!==authGeneration.current)return;setClasses(c);setStudents(s);setCodes(k);setDrafts(d);setAssignments(a);}
 async function task(run:()=>Promise<void>){if(busy||renderOwner!==editorOwner.current||renderEpoch!==authGeneration.current)return;const n=authGeneration.current;setBusy(true);try{await run();if(n===authGeneration.current)setMessage('Đã lưu trên máy chủ.');}catch(e){if(n===authGeneration.current)setMessage(e instanceof Error?e.message:'Chưa thực hiện được.');}finally{if(n===authGeneration.current)setBusy(false);}}
 useEffect(()=>{let active=true;const check=async()=>{const epoch=++authGeneration.current;setAuthorized(false);setBusy(false);setConfirmation(null);setRawCode('');setClasses([]);setStudents([]);setCodes([]);setDrafts([]);setAssignments([]);try{const u=await requireAdmin();if(!active||epoch!==authGeneration.current)return;if(editorOwner.current&&editorOwner.current!==u.id){setSelected(null);setReady(null);setHeldOwner(null);setName('');setSchool('');setSchoolClass('');setClassId('');setClassLabel('');setCodeStudent('');setOpens('');setDue('');}editorOwner.current=u.id;await refresh();if(active&&epoch===authGeneration.current)setAuthorized(true);}catch{if(active&&epoch===authGeneration.current)setMessage('Đăng nhập quản trị đề thi trước khi mở BTVN.');}};void check();const b=requireBackend(),{data}=b.auth.onAuthStateChange((_event,session)=>{if(!session){authGeneration.current++;setAuthorized(false);setConfirmation(null);setRawCode('');setClasses([]);setStudents([]);setCodes([]);setDrafts([]);setAssignments([]);}else{queueMicrotask(()=>{if(active)void check();});}});return()=>{active=false;authGeneration.current++;data.subscription.unsubscribe();};},[]);
 return <div className="hw-root ma-root"><SEO title="Quản trị BTVN | Minh Thành Math" description="Mã học sinh và giao BTVN" robots="noindex,nofollow"/><h1>Quản trị BTVN và mã học sinh</h1><div className="hw-actions"><Link href="/quan-tri/de-thi">Quản trị đề thi · đăng nhập</Link><Link href="/btvn">Mở trang BTVN học sinh</Link></div>{!authorized?<p role="status">{message}</p>:<>
 <section className="hw-panel"><h2>Lớp tại trung tâm</h2><form onSubmit={e=>{e.preventDefault();void task(async()=>{await ownedRpc('mtm_hw_admin_class',{p_label:classLabel,p_grade:grade});setClassLabel('');await refresh();});}}><label>Tên lớp MTM<input required maxLength={100} value={classLabel} onChange={e=>setClassLabel(e.target.value)}/></label><label>Khối<select value={grade} onChange={e=>setGrade(Number(e.target.value))}>{[10,11,12].map(g=><option key={g} value={g}>{g}</option>)}</select></label><button disabled={busy}>Tạo lớp</button></form></section>
 <section className="hw-panel"><h2>Hồ sơ và mã học sinh</h2><p>Hồ sơ chỉ hiển thị cho quản trị và người có mã hợp lệ. Bảng tháng dùng mã hiển thị riêng. Mã cấp lại đóng mã/phiên cũ và giữ lịch sử.</p><form onSubmit={e=>{e.preventDefault();void task(async()=>{await ownedRpc('mtm_hw_admin_student',{p_id:null,p_class_id:classId,p_name:name,p_school:school,p_school_class:schoolClass});setName('');setSchool('');setSchoolClass('');await refresh();});}}><label>Lớp MTM<select required value={classId} onChange={e=>setClassId(e.target.value)}><option value="">Chọn lớp</option>{classes.map(c=><option key={c.id} value={c.id}>{c.label} · khối {c.grade}</option>)}</select></label><label>Họ tên<input required maxLength={200} value={name} onChange={e=>setName(e.target.value)}/></label><label>Trường<input required maxLength={200} value={school} onChange={e=>setSchool(e.target.value)}/></label><label>Lớp tại trường<input required maxLength={100} value={schoolClass} onChange={e=>setSchoolClass(e.target.value)}/></label><button disabled={busy}>Tạo hồ sơ</button></form>
 {rawCode&&<section role="status"><h3>Mã vừa cấp · {codeStudent}</h3><p>Mã chỉ hiển thị lần này. Thành chuyển riêng cho đúng học sinh; không đưa vào bảng công khai.</p><input aria-label="Mã vừa cấp" type="password" readOnly value={rawCode}/><button onClick={()=>void navigator.clipboard.writeText(rawCode).then(()=>setMessage('Đã sao chép mã để Thành chuyển riêng.')).catch(()=>setMessage('Chưa sao chép được.'))}>Sao chép mã</button><button onClick={()=>setRawCode('')}>Ẩn mã</button></section>}
 <ul>{students.map(s=><li key={s.id}><strong>{s.profile?.fullName}</strong> · {s.profile?.centerClass} · {s.profile?.schoolClass}<button disabled={busy} onClick={()=>setConfirmation({message:'Cấp mã mới trong 90 ngày? Mã và phiên cũ ngừng dùng; lịch sử được giữ.',run:async()=>{const r=await ownedRpc<{code:string}>('mtm_hw_admin_issue_code',{p_student_id:s.id,p_days:90});setRawCode(r.code);setCodeStudent(s.profile.fullName);await refresh();}})}>Cấp hoặc thay mã</button>{codes.filter(c=>c.studentId===s.id&&!c.revokedAt).map(c=><span key={c.id}> Hết hạn {date(c.expiresAt)} <button disabled={busy} onClick={()=>setConfirmation({message:'Thu hồi mã và đóng các phiên của mã này? Lịch sử giữ nguyên.',run:async()=>{await ownedRpc('mtm_hw_admin_revoke_code',{p_code_id:c.id});setRawCode('');await refresh();}})}>Thu hồi mã</button></span>)}</li>)}</ul></section>
 <section className="hw-panel"><h2>Đề BTVN riêng</h2><button disabled={!!selected||busy} onClick={()=>{setHeldOwner(editorOwner.current);setSelected(fresh());setReady(null);setKey(n=>n+1);}}>Tạo đề BTVN mới</button><ul>{drafts.map(d=><li key={d.id}>{d.payload.title||'Bản nháp chưa tên'} · lần sửa {d.revision}<button disabled={!!selected||busy} onClick={()=>{setHeldOwner(editorOwner.current);setSelected(d);setReady(null);setKey(n=>n+1);}}>Mở bản nháp</button></li>)}</ul><p>Lưu và đóng bản đang sửa trước khi mở bản khác. PDF và khóa BTVN được lưu riêng với đề tự luyện công khai.</p></section>

 {ready&&<section className="hw-panel"><h2>Giao {ready.draft.title}</h2><form onSubmit={e=>{e.preventDefault();const start=new Date(opens),end=new Date(due);if(!classId||!Number.isFinite(start.getTime())||!Number.isFinite(end.getTime())||end<=start){setMessage('Chọn lớp và hạn sau thời gian mở.');return;}setConfirmation({message:`Giao bản đã kiểm cho lớp ${classes.find(c=>c.id===classId)?.label}, mở ${date(start.toISOString())}, hạn ${date(end.toISOString())}?`,run:async()=>{await ownedRpc('mtm_hw_admin_assign',{p_draft_id:ready.draft.id,p_revision:ready.revision,p_class_id:classId,p_opens:start.toISOString(),p_due:end.toISOString(),p_weight:weight,p_rank_eligible:ranked});setReady(null);await refresh();}});}}><label>Lớp được giao<select required value={classId} onChange={e=>setClassId(e.target.value)}><option value="">Chọn lớp</option>{classes.filter(c=>c.grade===ready.draft.grade).map(c=><option key={c.id} value={c.id}>{c.label}</option>)}</select></label><label>Mở bài (giờ thiết bị)<input type="datetime-local" required value={opens} onChange={e=>setOpens(e.target.value)}/></label><label>Hạn bài (giờ thiết bị)<input type="datetime-local" required value={due} onChange={e=>setDue(e.target.value)}/></label><p>Chỉ học sinh đã thuộc lớp trước thời gian mở bài mới được so hạng cùng tập BTVN. Lượt 1 cần nộp đúng hạn; luyện lại giữ lịch sử và không cộng điểm thưởng.</p><label>Trọng số tháng<input type="number" required min={1} max={100} value={weight} onChange={e=>setWeight(Number(e.target.value))}/></label><label><input type="checkbox" checked={ranked} onChange={e=>setRanked(e.target.checked)}/>Tính lượt 1 nộp đúng hạn vào bảng tháng</label><button className="hw-primary" disabled={busy}>Xác nhận giao BTVN</button></form></section>}
 <section className="hw-panel"><h2>BTVN đã giao</h2>{assignments.map(a=><article key={a.id}><h3>{a.title}</h3><p>{classes.find(c=>c.id===a.classId)?.label} · {date(a.opensAt)} → {date(a.dueAt)} · {a.visible?'Đang hiện':'Đang ẩn'}</p><button disabled={busy} onClick={()=>setConfirmation({message:a.visible?'Ẩn khỏi lượt bắt đầu mới? Lượt cũ và bảng tháng vẫn được giữ.':'Hiện lại BTVN cho lớp?',run:async()=>{await ownedRpc('mtm_hw_admin_visibility',{p_assignment:a.id,p_visible:!a.visible});await refresh();}})}>{a.visible?'Ẩn bài':'Hiện bài'}</button></article>)}</section><p role="status">{message}</p>
 </>} {selected&&<div hidden={!authorized}><ExamEditor key={key} initial={selected} actions={actions} onSaved={r=>{if(editorOwner.current===heldOwner&&editorEpoch===authGeneration.current)setDrafts(ds=>[r,...ds.filter(x=>x.id!==r.id)]);}} onPublished={()=>{}} onEdited={(d,rev)=>{if(editorEpoch===authGeneration.current&&heldOwner===editorOwner.current)setReady(current=>current&&(JSON.stringify(current.draft)!==JSON.stringify(d)||current.revision!==rev)?null:current);}} onPublishDraft={async(d,revision)=>{if(editorOwner.current!==heldOwner||editorEpoch!==authGeneration.current)throw Error('Tài khoản quản trị đã đổi.');setReady({draft:d,revision});}}/><button onClick={()=>setConfirmation({message:'Đóng bản sửa BTVN? Hãy lưu để giữ thay đổi đang nhập.',run:async()=>{setSelected(null);setReady(null);}})}>Đóng bản sửa</button></div>}{confirmation&&<ExamConfirm title="Xác nhận quản trị BTVN" message={confirmation.message} confirmLabel="Xác nhận" onCancel={()=>setConfirmation(null)} onConfirm={()=>{if(renderEpoch!==authGeneration.current||renderOwner!==editorOwner.current)return;const run=confirmation.run;setConfirmation(null);void task(run);}}/>}</div>;
}
