import {useEffect,useRef,useState} from 'react';
import ExamConfirm from '../exams/ExamConfirm';
import {useUnsavedGuard} from '../exams/navigation-guard';
import {PdfViewer} from './HomeworkResult';
import type {Answers,Attempt,HomeworkApi,Result} from './types';
import {points} from './types';
export default function HomeworkAttempt({initial,session,api,onResult,onBack}:{initial:Attempt;session:string;api:HomeworkApi;onResult:(r:Result)=>void;onBack:()=>void}){
 const [answers,setAnswers]=useState<Answers>(initial.answers),[status,setStatus]=useState('Đã tải đáp án máy chủ.'),[busy,setBusy]=useState(false),[confirm,setConfirm]=useState(false),[selected,setSelected]=useState(0),[dirty,setDirty]=useState(false),[remaining,setRemaining]=useState(0);
 const [pendingWrites,setPendingWrites]=useState(0);
 const live=useRef(initial.answers),revision=useRef(initial.revision),saved=useRef(JSON.stringify(initial.answers)),queue=useRef<Promise<void>>(Promise.resolve()),pending=useRef(0),submitting=useRef(false),mounted=useRef(true),submissionKey=useRef(crypto.randomUUID()),anchor=useRef({at:performance.now(),server:Date.parse(initial.serverNow)}),deadline=Date.parse(initial.deadline);
 const leave=useUnsavedGuard(()=>dirty||busy||pending.current>0,'Đáp án chưa lưu trên máy chủ. Rời trang sẽ mất phần chưa lưu. Các đáp án máy chủ đã lưu sẽ được giữ.');
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
 useEffect(()=>{const tick=()=>setRemaining(Math.max(0,Math.ceil((deadline-anchor.current.server-(performance.now()-anchor.current.at))/1000)));tick();const timer=window.setInterval(tick,1000);return()=>clearInterval(timer);},[deadline]);
 function change(id:string,value:Answers[string]|undefined){if(submitting.current||remaining<=0)return;const next={...live.current};if(value===undefined)delete next[id];else next[id]=value;live.current=next;setAnswers(next);setDirty(JSON.stringify(next)!==saved.current||pending.current>0);setStatus('Có đáp án chưa lưu.');}
 function enqueueSave(){const snapshot=live.current;if(JSON.stringify(snapshot)===saved.current)return queue.current;
  pending.current++;setPendingWrites(pending.current);
  const job=queue.current.catch(()=>{}).then(async()=>{if(JSON.stringify(snapshot)===saved.current)return;setStatus('Đang lưu máy chủ…');const result=await api.save(session,initial.attemptId,revision.current,snapshot);revision.current=result.revision;saved.current=JSON.stringify(result.answers);if(result.serverNow)anchor.current={at:performance.now(),server:Date.parse(result.serverNow)};}).finally(()=>{pending.current--;if(mounted.current){setPendingWrites(pending.current);setDirty(JSON.stringify(live.current)!==saved.current||pending.current>0);if(JSON.stringify(live.current)===saved.current&&pending.current===0)setStatus('Đã lưu trên máy chủ.');}});queue.current=job;return job;
 }
 useEffect(()=>{if(!dirty||busy||remaining<=0)return;const timer=setTimeout(()=>void enqueueSave().catch(()=>{if(mounted.current)setStatus('Chưa lưu được. Đáp án đang nhập vẫn giữ trong tab này; bấm Lưu lại khi có mạng.');}),800);return()=>clearTimeout(timer);},[answers,busy,dirty,remaining<=0]);
 async function submit(){if(submitting.current)return;submitting.current=true;setBusy(true);setConfirm(false);try{await queue.current.catch(()=>{});const r=await api.submit(session,initial.attemptId,revision.current,live.current,submissionKey.current);setDirty(false);onResult(r);}catch(e){setStatus(e instanceof Error?e.message:'Chưa nộp được. Bài vẫn được giữ.');submitting.current=false;setBusy(false);}}
 const q=initial.exam.questions[selected],answered=initial.exam.questions.filter(q=>{const v=answers[q.id];return q.kind==='tf'?Array.isArray(v)&&v.every(a=>typeof a==='boolean'):typeof v==='string'&&v.trim().length>0;}).length;
 return <section className="hw-attempt">{leave}<header><h2>{initial.exam.title}</h2><p>Lượt {initial.attemptNumber} · {answered}/{initial.exam.questionCount} câu đã trả lời</p><p role="timer" aria-live="off" className="hw-clock">Còn {Math.floor(remaining/60)}:{String(remaining%60).padStart(2,'0')}</p><p>Thời gian và điểm được máy chủ xác nhận. {remaining===0?'Đã hết giờ: nộp để chấm bản máy chủ đã lưu.':'Hãy nộp trước khi bộ đếm về 0.'}</p></header>
 <div className="hw-workspace"><PdfViewer api={api} session={session} attempt={initial.attemptId} kind="questions"/><section className="hw-sheet"><h3>Phiếu trả lời</h3><nav className="hw-grid" aria-label="Chọn câu BTVN">{initial.exam.questions.map((x,i)=><button key={x.id} type="button" aria-current={i===selected?'step':undefined} onClick={()=>setSelected(i)}>{i+1}</button>)}</nav>
 <fieldset disabled={busy||remaining<=0}><legend>{q.sourceRef} · {points(q.maxMillipoints)} điểm</legend>{q.kind==='mc'?<div className="hw-options">{['A','B','C','D'].map(a=><label key={a} className={answers[q.id]===a?'chosen':''}><input type="radio" name={q.id} value={a} checked={answers[q.id]===a} onChange={()=>change(q.id,a)}/>{a}</label>)}</div>:q.kind==='tf'?<div>{[0,1,2,3].map(i=><fieldset key={i}><legend>Ý {String.fromCharCode(97+i)}</legend><div className="hw-options">{[true,false].map(v=><label key={String(v)}><input type="radio" name={q.id+'-'+i} checked={Array.isArray(answers[q.id])&&(answers[q.id] as Array<boolean|null>)[i]===v} onChange={()=>{const next=Array.isArray(live.current[q.id])?[...live.current[q.id] as Array<boolean|null>]:[null,null,null,null];next[i]=v;change(q.id,next);}}/>{v?'Đúng':'Sai'}</label>)}</div></fieldset>)}</div>:<label>Đáp án ngắn<input maxLength={100} autoComplete="off" value={String(answers[q.id]??'')} onChange={e=>change(q.id,e.target.value)}/><small>{q.mode==='rational'?'Nhập số nguyên hoặc phân số a/b; không kèm đơn vị.':q.mode==='exact'?'Nhập đúng nội dung theo yêu cầu của đề.':'Nhập số; dùng dấu phẩy hoặc dấu chấm cho phần thập phân.'}</small></label>}
 <button type="button" onClick={()=>change(q.id,q.kind==='mc'?undefined:q.kind==='tf'?[null,null,null,null]:'')}>Xóa đáp án câu này</button></fieldset>
 <div className="hw-actions"><button type="button" disabled={selected===0} onClick={()=>setSelected(i=>i-1)}>Câu trước</button><button type="button" disabled={selected===initial.exam.questionCount-1} onClick={()=>setSelected(i=>i+1)}>Câu tiếp</button></div><p role="status">{status}</p><div className="hw-actions"><button disabled={busy||remaining===0} onClick={()=>void enqueueSave().catch(e=>setStatus(e.message))}>Lưu lại đáp án</button><button className="hw-primary" disabled={busy} onClick={()=>setConfirm(true)}>Nộp bài</button><button disabled={busy||dirty||pendingWrites>0} onClick={onBack}>Về danh sách</button></div></section></div>
 {confirm&&<ExamConfirm title="Nộp BTVN?" message={`Đã trả lời ${answered}/${initial.exam.questionCount} câu. Sau khi nộp, lượt này được giữ và không sửa đáp án.`} confirmLabel="Xác nhận nộp bài" onCancel={()=>setConfirm(false)} onConfirm={()=>void submit()}/>}</section>;
}
