import {useEffect,useRef,useState} from 'react';
import {getDocument,GlobalWorkerOptions,AnnotationMode,type PDFDocumentProxy,type RenderTask} from 'pdfjs-dist';
import workerUrl from 'pdfjs-dist/build/pdf.worker.min.mjs?url';
import type {HomeworkApi} from './types';
GlobalWorkerOptions.workerSrc=workerUrl;
export default function PrivatePdf({api,session,attempt,kind}:{api:HomeworkApi;session:string;attempt:string;kind:'questions'|'solutions'}){
 const [doc,setDoc]=useState<PDFDocumentProxy|null>(null),[page,setPage]=useState(1),[jump,setJump]=useState('1'),[zoom,setZoom]=useState(100),[width,setWidth]=useState(600),[busy,setBusy]=useState(true),[shown,setShown]=useState(0),[text,setText]=useState(''),[error,setError]=useState(''),[retry,setRetry]=useState(0);
 const host=useRef<HTMLDivElement>(null),sheet=useRef<HTMLDivElement>(null),label=kind==='questions'?'PDF đề':'PDF lời giải';
 useEffect(()=>{const node=host.current;if(!node)return;const observer=new ResizeObserver(entries=>setWidth(Math.max(200,Math.floor(entries[0].contentRect.width))));observer.observe(node);return()=>observer.disconnect();},[]);
 useEffect(()=>{let active=true,task:ReturnType<typeof getDocument>|undefined;setDoc(null);setPage(1);setJump('1');setShown(0);setText('');setError('');setBusy(true);sheet.current?.replaceChildren();
  const timeout=window.setTimeout(()=>{if(active){active=false;setError('Tải PDF quá lâu. Bài và đáp án đã lưu vẫn được giữ.');setBusy(false);void task?.destroy().catch(()=>{});}},25000);
  void(async()=>{try{const blob=await api.pdf(session,attempt,kind);if(!active)return;const data=new Uint8Array(await blob.arrayBuffer());if(!active)return;if(blob.type!=='application/pdf'||data.length<8||data.length>15728640||new TextDecoder().decode(data.slice(0,5))!=='%PDF-')throw Error('Tệp PDF không hợp lệ.');task=getDocument({data,enableXfa:false,stopAtErrors:true,useSystemFonts:true,maxImageSize:16000000});const loaded=await task.promise;if(!active)return;if(loaded.numPages<1||loaded.numPages>1000)throw Error('Số trang PDF chưa hợp lệ.');window.clearTimeout(timeout);setDoc(loaded);}catch{if(active){window.clearTimeout(timeout);setError('Chưa hiển thị được PDF riêng. Thử tải lại; bài đã lưu vẫn được giữ.');setBusy(false);}}})();
  return()=>{active=false;window.clearTimeout(timeout);sheet.current?.replaceChildren();void task?.destroy().catch(()=>{});};
 },[api,session,attempt,kind,retry]);
 useEffect(()=>{if(!doc||!sheet.current)return;let active=true,render:RenderTask|undefined;setBusy(true);setShown(0);setError('');setText('');sheet.current.replaceChildren();
  void(async()=>{try{const pdfPage=await doc.getPage(page);if(!active)return;const natural=pdfPage.getViewport({scale:1}),viewport=pdfPage.getViewport({scale:Math.min(1050,Math.max(180,width-8))/natural.width*(zoom/100)}),density=Math.min(2,window.devicePixelRatio||1,Math.sqrt(6000000/(viewport.width*viewport.height)));
   const canvas=document.createElement('canvas'),context=canvas.getContext('2d',{alpha:false});if(!context)throw Error('Canvas unavailable');canvas.width=Math.ceil(viewport.width*density);canvas.height=Math.ceil(viewport.height*density);canvas.style.width=Math.ceil(viewport.width)+'px';canvas.style.height=Math.ceil(viewport.height)+'px';canvas.setAttribute('role','img');canvas.setAttribute('aria-label',`${label}, trang ${page}/${doc.numPages}`);canvas.setAttribute('aria-busy','true');sheet.current?.replaceChildren(canvas);
   render=pdfPage.render({canvas,viewport,transform:density!==1?[density,0,0,density,0,0]:undefined,annotationMode:AnnotationMode.DISABLE});await render.promise;if(!active)return;canvas.dataset.homeworkPdfPage=String(page);canvas.setAttribute('aria-busy','false');setShown(page);setBusy(false);
   try{const extracted=await pdfPage.getTextContent();if(active)setText(extracted.items.filter(item=>'str'in item).map(item=>'str'in item?item.str:'').join(' '));}catch{if(active)setText('Trang này chưa có lớp chữ trích xuất; đọc bản gốc phía trên.');}
  }catch(e){if(active&&!(e instanceof Error&&e.name==='RenderingCancelledException')){sheet.current?.replaceChildren();setError('Chưa dựng được trang PDF. Thử tải lại; bài đã lưu vẫn được giữ.');setBusy(false);}}})();
  return()=>{active=false;render?.cancel();};
 },[doc,page,width,zoom,label]);
 function go(n:number){if(!doc||n<1||n>doc.numPages)return;setPage(n);setJump(String(n));}
 return <section className="hw-pdf" aria-label={label}><h3>{label}</h3><div className="hw-pdf-controls" role="group" aria-label={`Điều khiển ${label}`}><button type="button" disabled={!doc||page<=1} onClick={()=>go(page-1)}>Trang trước</button><form onSubmit={e=>{e.preventDefault();const n=Number(jump);if(!/^\d+$/.test(jump)||!doc||n<1||n>doc.numPages){setJump(String(page));return;}go(n);}}><label>Trang<input aria-label={`Số trang ${label}`} inputMode="numeric" maxLength={4} disabled={!doc} value={jump} onChange={e=>setJump(e.target.value)}/></label><span>/ {doc?.numPages??'—'}</span><button type="submit" disabled={!doc}>Đến trang</button></form><button type="button" disabled={!doc||page>=doc.numPages} onClick={()=>go(page+1)}>Trang sau</button><label>Thu/phóng<select aria-label={`Thu/phóng ${label}`} value={zoom} disabled={!doc} onChange={e=>setZoom(Number(e.target.value))}>{[100,125,150,200].map(n=><option key={n} value={n}>{n===100?'Vừa khung':`${n}%`}</option>)}</select></label></div>
 <p role="status" aria-live="polite">{error?'Chưa đọc được PDF':busy?doc?`Đang dựng trang ${page}…`:'Đang tải PDF riêng…':`Đã hiển thị trang ${shown}/${doc?.numPages}`}</p>{error&&<p role="alert">{error} <button type="button" onClick={()=>setRetry(n=>n+1)}>Tải lại PDF</button></p>}<div ref={host} className="hw-pdf-scroll" tabIndex={0} aria-label={label+'; cuộn để đọc trang'} aria-busy={busy}><div ref={sheet}/></div>{shown>0&&!busy&&!error&&<details><summary>Văn bản trang {shown}</summary><p>{text||'Trang ảnh quét không có lớp chữ; xem PDF gốc phía trên.'}</p></details>}</section>;
}
