import {useRef,useState} from 'react';
import {Link} from '../../migration/navigation';
import {SEO} from '../../components/SEO';
import {homeworkApi,HomeworkError} from './api';
import type {Assignment,Attempt,History,HomeworkApi,Profile,Rank,Result} from './types';
import {points,time,date} from './types';
import HomeworkAttempt from './HomeworkAttempt';
import HomeworkResult from './HomeworkResult';
import './homework.css';
export default function StudentHomework({api=homeworkApi,initialCode=''}:{api?:HomeworkApi;initialCode?:string}){
 const [code,setCode]=useState(initialCode),[challenge,setChallenge]=useState(''),[profile,setProfile]=useState<Profile|null>(null),[session,setSession]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[assignments,setAssignments]=useState<Assignment[]>([]),[history,setHistory]=useState<History[]>([]),[ranks,setRanks]=useState<Rank[]>([]),[month,setMonth]=useState(()=>(()=>{const parts=new Intl.DateTimeFormat('en',{timeZone:'Asia/Ho_Chi_Minh',year:'numeric',month:'2-digit'}).formatToParts(new Date());return parts.find(p=>p.type==='year')!.value+'-'+parts.find(p=>p.type==='month')!.value;})()),[attempt,setAttempt]=useState<Attempt|null>(null),[result,setResult]=useState<Result|null>(null);
 const generation=useRef(0),refreshSequence=useRef(0);
 async function task(run:()=>Promise<void>){if(busy)return;setBusy(true);setMessage('Đang xử lý…');try{await run();setMessage('');}catch(e){if(e instanceof HomeworkError&&e.code==='42501')clear();setMessage(e instanceof Error?e.message:'Chưa kết nối được.');}finally{setBusy(false);}}
 async function refresh(token=session,p=profile,m=month){if(!p||!token)return;const current=generation.current,sequence=++refreshSequence.current;const [a,h,r]=await Promise.all([api.assignments(token),api.history(token),api.leaderboard(p.classId,m)]);if(current!==generation.current||sequence!==refreshSequence.current)return;setAssignments(a);setHistory(h);setRanks(r);}
 function clear(){generation.current++;refreshSequence.current++;setCode('');setChallenge('');setProfile(null);setSession('');setAssignments([]);setHistory([]);setRanks([]);setAttempt(null);setResult(null);}
 return <div className="hw-root"><SEO title="BTVN và lịch sử | Minh Thành Math" description="BTVN MTM theo mã lớp cấp" robots="noindex,nofollow"/><header><p>Minh Thành Math</p><h1>Bài tập về nhà</h1><Link href="/thi-thu">Thi thử và luyện đề</Link></header>
 {!session?<section className="hw-panel">{!challenge?<><h2>Nhập mã học sinh</h2><p>Dùng mã do lớp cấp để xem hồ sơ và BTVN của mình. Không dùng mã của bạn khác.</p><form onSubmit={e=>{e.preventDefault();void task(async()=>{const r=await api.resolve(code);setCode('');if(!r.ok||!r.challenge||!r.profile)throw Error('Mã không hợp lệ hoặc chưa dùng được. Kiểm tra mã với giáo viên.');setProfile(r.profile);setChallenge(r.challenge);});}}><label>Mã học sinh<input type="password" autoComplete="off" maxLength={80} required value={code} onChange={e=>setCode(e.target.value)}/></label><button className="hw-primary" disabled={busy}>Kiểm tra mã</button></form></>:<><h2>Xác nhận thông tin của em</h2><dl><dt>Họ tên</dt><dd>{profile?.fullName}</dd><dt>Trường</dt><dd>{profile?.school}</dd><dt>Lớp tại trường</dt><dd>{profile?.schoolClass}</dd><dt>Lớp tại MTM</dt><dd>{profile?.centerClass}</dd></dl><p>Chỉ xác nhận khi thông tin đúng. Mã không được lưu vào địa chỉ trang hoặc lịch sử làm bài.</p><div className="hw-actions"><button disabled={busy} onClick={clear}>Thông tin chưa đúng</button><button className="hw-primary" disabled={busy} onClick={()=>void task(async()=>{const r=await api.confirm(challenge);if(!r.ok||!r.session||!r.profile){clear();throw Error('Xác nhận đã hết hạn. Nhập lại mã.');}generation.current++;setSession(r.session);setChallenge('');setProfile(r.profile);await refresh(r.session,r.profile);})}>Đúng thông tin · vào BTVN</button></div></>}<p>Phiên được giữ trong bộ nhớ tab. Tải lại trang cần nhập lại mã; bài đã lưu trên máy chủ vẫn được giữ.</p></section>:<><section className="hw-profile"><strong>{profile?.fullName}</strong><span>{profile?.centerClass} · Mã hiển thị bảng: {profile?.publicAlias}</span><button disabled={busy||!!attempt} onClick={()=>void task(async()=>{await api.logout(session);clear();})}>Thoát phiên học sinh</button></section>
 {attempt?<HomeworkAttempt key={attempt.attemptId} initial={attempt} session={session} api={api} onResult={r=>{setAttempt(null);setResult(r);void refresh().catch(e=>setMessage(e.message));}} onBack={()=>{setAttempt(null);void task(()=>refresh());}}/>:result?<HomeworkResult result={result} api={api} session={session} onBack={()=>{setResult(null);void task(()=>refresh());}}/>:<><section className="hw-panel"><h2>Bảng xếp hạng tháng</h2><label>Tháng<input type="month" disabled={busy} value={month} onChange={e=>{const m=e.target.value;setMonth(m);if(/^\d{4}-\d{2}$/.test(m))void task(()=>refresh(session,profile,m));}}/></label><p>Cùng lớp và cùng tập BTVN mới so hạng. Bài chưa làm tính 0; chỉ lượt 1 nộp đúng hạn và đủ điều kiện tính điểm thưởng. Luyện lại tăng số lượt nhưng không cộng điểm xếp hạng. Cùng điểm cùng hạng; giáo viên xét thưởng cuối tháng.</p>{!ranks.length?<p>Chưa có bảng xếp hạng trong tháng này.</p>:<div className="hw-table"><table><caption>{profile?.centerClass} · {month} · chỉ hiển thị mã bảng</caption><thead><tr><th scope="col">Nhóm</th><th scope="col">Hạng</th><th scope="col">Mã bảng</th><th scope="col">Điểm %</th><th scope="col">Bài hoàn thành</th><th scope="col">Lượt</th><th scope="col">Thời gian tính hạng</th></tr></thead><tbody>{ranks.map(r=><tr key={r.alias+'-'+r.cohort} className={r.alias===profile?.publicAlias?'hw-own':''}><td>{r.cohort.slice(0,8)}</td><td>{r.rank}</td><th scope="row">{r.alias}{r.alias===profile?.publicAlias?' (em)':''}</th><td>{r.percentage.toLocaleString('vi-VN',{maximumFractionDigits:2})}%</td><td>{r.completedCount}/{r.assignedCount}</td><td>{r.attemptCount}</td><td>{time(r.elapsedMs)}</td></tr>)}</tbody></table></div>}</section>
 <section className="hw-panel"><h2>BTVN của lớp</h2><button disabled={busy} onClick={()=>void task(()=>refresh())}>Tải lại bài và lịch sử</button>{!assignments.length?<p>Chưa có BTVN được giao.</p>:assignments.map(a=>{const done=history.filter(h=>h.assignmentId===a.id);return <article className="hw-assignment" key={a.id}><h3>{a.title}</h3><p>{a.questionCount} câu · {a.durationMinutes} phút · mở {date(a.opensAt)} · hạn {date(a.dueAt)}</p><p>{done.length?`Đã nộp ${done.length} lượt; gần nhất ${points(done[0].score.earnedMillipoints)}/10.`:'Chưa có lượt nộp.'}</p><button disabled={busy} onClick={()=>void task(async()=>{setAttempt(await api.start(session,a.id));setResult(null);})}>Làm hoặc tiếp tục bài</button></article>;})}</section>
 <section className="hw-panel"><h2>Lịch sử của em</h2><p>{history.length} lượt gần nhất đã nộp · đồng bộ theo mã học sinh.</p>{history.map(h=><article className="hw-assignment" key={h.attemptId}><h3>{h.title}</h3><p>Lượt {h.attemptNumber} · {points(h.score.earnedMillipoints)}/10 · {time(h.elapsedMs)} · {date(h.submittedAt)}</p><button disabled={busy} onClick={()=>void task(async()=>setResult(await api.result(session,h.attemptId)))}>Xem điểm và đáp án lượt này</button></article>)}</section></>}
 </>}
 <p className="hw-message" role="status">{message}</p></div>;
}
