import {useEffect,useState} from 'react';
import {CalendarDays,ArrowUpRight} from 'lucide-react';
import news from '../data/public-news.json';
import {activePublicNews} from './public-news';
import {activeFeedNews,fetchPublicNews,vietnamDate,type FeedNews} from './public-news-feed';
import './mtm-news.css';
export function MtmNewsSection(){const [now,setNow]=useState<number|null>(null),[remote,setRemote]=useState<FeedNews[]>([]),[status,setStatus]=useState<'loading'|'ready'|'fallback'>('loading'),[stamp,setStamp]=useState(''),[retry,setRetry]=useState(0);
 useEffect(()=>{let alive=true;const abort=new AbortController();setStatus('loading');const timeout=setTimeout(()=>abort.abort(),10000);fetchPublicNews(abort.signal).then(result=>{if(alive){setRemote(result.items);setStamp(result.generated_at);setStatus('ready')}}).catch(()=>{if(alive){setRemote([]);setStamp('');setStatus('fallback')}}).finally(()=>clearTimeout(timeout));return()=>{alive=false;abort.abort();clearTimeout(timeout)}},[retry]);
 useEffect(()=>{setNow(Date.now());const clock=setInterval(()=>setNow(Date.now()),30000);const refresh=setInterval(()=>setRetry(x=>x+1),120000);return()=>{clearInterval(clock);clearInterval(refresh)}},[]);
 const live=now===null?[]:activeFeedNews(remote,now),saved=now===null?[]:activePublicNews(news,now);const cards=status==='ready'?live.map(n=>({id:n.id,title:n.title,description:n.description,label:n.kind==='EVENT'?'Sự kiện':n.kind==='DAILY'?'Bản tin ngày':'Bản tin tuần',time:n.kind==='EVENT'?vietnamDate(n.event_start!)+' – '+vietnamDate(n.event_end!):'Kỳ tin: '+n.period_start+' – '+n.period_end,href:n.href})):status==='fallback'?saved.map(n=>({id:n.id,title:n.title,description:n.description,label:n.kind,time:n.date_label+' · '+n.schedule,href:n.href})):[];
 return <section className="mtm-news" aria-labelledby="mtm-news-title"><div className="mtm-shell"><p className="mtm-news-eyebrow">HẸN GẶP Ở MTM</p><h2 id="mtm-news-title">Bản tin MTM</h2><p className="mtm-news-intro">Tin từ trung tâm và những lịch hẹn sắp tới. Thời gian theo giờ Việt Nam.</p>
 <p role="status">{status==='loading'?'Đang đọc bản tin từ trung tâm…':status==='fallback'?'Chưa kết nối được nguồn cập nhật. Các lịch bên dưới là thông tin đã lưu, chưa xác nhận thay đổi mới nhất.':`Đã đọc nguồn bản tin lúc ${vietnamDate(stamp)}.`}</p>{status==='fallback'&&<button type="button" onClick={()=>setRetry(x=>x+1)}>Thử cập nhật lại</button>}
 <div className="mtm-news-grid">{cards.map(n=><article key={n.id} className="mtm-news-card"><div className="mtm-news-top"><CalendarDays size={26} aria-hidden="true"/><span>{n.label}</span></div><h3>{n.title}</h3><p className="mtm-news-time">{n.time}</p><p style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{n.description}</p><a href={n.href}>Liên hệ tư vấn<ArrowUpRight size={18} aria-hidden="true"/></a></article>)}</div>
 {status==='ready'&&!cards.length&&<p>Hiện chưa có bản tin đang hiển thị.</p>}{status==='fallback'&&!cards.length&&<p>Không có lịch đã lưu còn hiệu lực để hiển thị. Bạn có thể liên hệ MTM để xác nhận.</p>}{cards.length>0&&<p className="mtm-news-note">Liên hệ MTM để xác nhận lịch trước khi tham gia.</p>}</div></section>
}
