export const PUBLIC_NEWS_ENDPOINT='https://mtm-vao-ca.thanh-tm-fyu.chatgpt.site/api/public-news';
export type FeedNews={id:string;version:number;kind:'DAILY'|'WEEKLY'|'EVENT';title:string;description:string;visible_from:string;expires_at:string;event_start:string|null;event_end:string|null;period_start:string|null;period_end:string|null;timezone:'Asia/Ho_Chi_Minh';href:'#register'};
const iso=(v:unknown):v is string=>typeof v==='string'&&/(Z|[+-]\d{2}:\d{2})$/.test(v)&&Number.isFinite(Date.parse(v));
export function parseFeedNews(v:unknown):FeedNews|null{if(!v||typeof v!=='object'||Array.isArray(v))return null;const x=v as Record<string,unknown>;if(typeof x.id!=='string'||x.id.length>100||!Number.isInteger(x.version)||(x.version as number)<1||!['DAILY','WEEKLY','EVENT'].includes(x.kind as string)||typeof x.title!=='string'||!x.title.trim()||x.title.length>120||typeof x.description!=='string'||x.description.length>3000||!iso(x.visible_from)||!iso(x.expires_at)||Date.parse(x.expires_at)<=Date.parse(x.visible_from)||x.timezone!=='Asia/Ho_Chi_Minh'||x.href!=='#register')return null;
 const event=x.kind==='EVENT';if(event&&(!iso(x.event_start)||!iso(x.event_end)||Date.parse(x.event_end)<=Date.parse(x.event_start)))return null;
 if(!event&&(typeof x.period_start!=='string'||typeof x.period_end!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(x.period_start)||!/^\d{4}-\d{2}-\d{2}$/.test(x.period_end)||x.period_end<x.period_start))return null;
 return {id:x.id,version:x.version as number,kind:x.kind as FeedNews['kind'],title:x.title,description:x.description,visible_from:x.visible_from,expires_at:x.expires_at,event_start:event?x.event_start as string:null,event_end:event?x.event_end as string:null,period_start:event?null:x.period_start as string,period_end:event?null:x.period_end as string,timezone:'Asia/Ho_Chi_Minh',href:'#register'};
}
export function activeFeedNews(items:FeedNews[],now:number){return Number.isFinite(now)?items.filter(x=>Date.parse(x.visible_from)<=now&&now<Date.parse(x.expires_at)):[]}
export function vietnamDate(value:string){return new Intl.DateTimeFormat('vi-VN',{timeZone:'Asia/Ho_Chi_Minh',day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(value))}
export async function fetchPublicNews(signal:AbortSignal,fetcher:typeof fetch=fetch):Promise<{items:FeedNews[];generated_at:string}>{const all:FeedNews[]=[];const seen=new Set<string>();let cursor:string|null=null,generated='';for(let page=0;page<20;page++){const url=new URL(PUBLIC_NEWS_ENDPOINT);if(cursor)url.searchParams.set('cursor',cursor);const r=await fetcher(url.toString(),{method:'GET',credentials:'omit',cache:'no-store',redirect:'error',signal});if(!r.ok)throw Error('FEED_UNAVAILABLE');const raw=await r.text();if(raw.length>300000)throw Error('FEED_TOO_LARGE');const j=JSON.parse(raw);if(!j||!Array.isArray(j.items)||j.items.length>50||!iso(j.generated_at)||!(j.next_cursor===null||typeof j.next_cursor==='string'&&j.next_cursor.length>0&&j.next_cursor.length<=100))throw Error('FEED_INVALID');for(const row of j.items){const item=parseFeedNews(row);if(!item)throw Error('FEED_INVALID');const at=all.findIndex(x=>x.id===item.id);if(at<0)all.push(item);else if(item.version>all[at].version)all[at]=item;}generated=j.generated_at;if(j.next_cursor===null)return {items:all,generated_at:generated};if(seen.has(j.next_cursor))throw Error('CURSOR_LOOP');seen.add(j.next_cursor);cursor=j.next_cursor;}throw Error('FEED_INCOMPLETE')}
