export type CalendarSession={class_name:string;group:string;weekday:number;time:string};
const DAY=86400000;
export function referenceDate(start:string,weekday:number){if(!/^\d{4}-\d{2}-\d{2}$/.test(start)||!Number.isInteger(weekday)||weekday<1||weekday>7)throw Error('Ngày tham chiếu không hợp lệ.');const t=Date.parse(start+'T00:00:00Z');if(!Number.isFinite(t)||new Date(t).toISOString().slice(0,10)!==start)throw Error('Ngày tham chiếu không tồn tại.');const dow=new Date(t).getUTCDay()||7;return new Date(t+((weekday-dow+7)%7)*DAY).toISOString().slice(0,10)}
export const escapeCalendarText=(v:string)=>v.replace(/\\/g,'\\\\').replace(/\r\n|\r|\n/g,'\\n').replace(/;/g,'\\;').replace(/,/g,'\\,');
export function foldCalendarLine(line:string){const out:string[]=[];let chunk='',bytes=0;for(const ch of line){const size=new TextEncoder().encode(ch).length;if(bytes+size>75){out.push(chunk);chunk=' ';bytes=1}chunk+=ch;bytes+=size}out.push(chunk);return out.join('\r\n')}
export async function createTimetableICS(rows:CalendarSession[],start='2026-09-30'){
 if(!rows.length)throw Error('Không có ca phù hợp để tải.');referenceDate(start,1);
 const lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Minh Thanh Math//Lich du kien//VI','CALSCALE:GREGORIAN','X-WR-CALNAME:Lịch MTM dự kiến'];const seen=new Set<string>();
 for(const row of rows){const date=referenceDate(start,row.weekday),m=row.time.match(/^(\d{2}):(\d{2})[–-](\d{2}):(\d{2})$/);if(!m)throw Error('Giờ học chưa hợp lệ.');const parts=m.slice(1).map(Number);if(parts[0]>23||parts[2]>23||parts[1]>59||parts[3]>59||parts[2]*60+parts[3]<=parts[0]*60+parts[1])throw Error('Giờ kết thúc phải sau giờ bắt đầu trong ngày.');const key=JSON.stringify([date,row.class_name,row.group,row.time]);if(seen.has(key))continue;seen.add(key);const uid=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(key)))).map(x=>x.toString(16).padStart(2,'0')).join('');const utc=(h:string,min:string)=>new Date(Date.parse(date+'T'+h+':'+min+':00+07:00')).toISOString().replace(/[-:]/g,'').replace('.000','');
 lines.push('BEGIN:VEVENT','UID:'+uid+'@minhthanhmath.vn','DTSTAMP:20260930T000000Z','DTSTART:'+utc(m[1],m[2]),'DTEND:'+utc(m[3],m[4]),'SUMMARY:'+escapeCalendarText('Dự kiến · '+row.class_name),'DESCRIPTION:'+escapeCalendarText('Lịch tham chiếu 7 ngày từ '+start+'. Giờ Việt Nam. Xác nhận với MTM trước khi đến lớp. Nhóm: '+row.group),'STATUS:TENTATIVE','END:VEVENT');
 }
 lines.push('END:VCALENDAR');return lines.map(foldCalendarLine).join('\r\n')+'\r\n';
}
export function printTimetableOnly(element:HTMLElement){const previous=document.getElementById('mtm-print-only');if(previous)return;const copy=element.cloneNode(true) as HTMLElement;copy.id='mtm-print-only';copy.querySelectorAll('.mtm-timetable-filters,.mtm-calendar-actions,button,a').forEach(n=>n.remove());document.body.appendChild(copy);document.body.classList.add('mtm-printing');const cleanup=()=>{copy.remove();document.body.classList.remove('mtm-printing');window.removeEventListener('afterprint',cleanup)};window.addEventListener('afterprint',cleanup);try{window.print()}finally{cleanup()}}
