import {useEffect,useState,useRef} from 'react';
import {importKeyText,keyTemplate,importLayoutKey,layoutKeyTemplate,type KeySuggestion} from './key-import';
import type {ExamSection} from '../exams/flexible-profile';
import {layoutRows,LEGACY_LAYOUT} from './layout';
export default function KeyImport({pdfText,layout,shortMode,onApply}:{pdfText:string;layout?:ExamSection[];shortMode?:string;onApply:(s:KeySuggestion)=>void}){
 const [suggestion,setSuggestion]=useState<(KeySuggestion&{signature:string})|null>(null),[message,setMessage]=useState(''),[paste,setPaste]=useState('');
 const signature=JSON.stringify([layout,shortMode,pdfText]),context=useRef(signature),generation=useRef(0);context.current=signature;
 function read(text:string,request=generation.current,captured=signature){if(request!==generation.current||captured!==context.current)return;try{setSuggestion({...layout?importLayoutKey(text,layout,shortMode):importKeyText(text),signature:captured});setMessage('');}catch(e){setSuggestion(null);setMessage((e as Error).message);}}
 useEffect(()=>{generation.current++;setSuggestion(null);if(pdfText)read(pdfText);},[pdfText,layout,shortMode]);
 const displayRows=layoutRows(layout??LEGACY_LAYOUT);
 return <section aria-label="Nhập nhanh khóa chấm"><h3>Nhập khóa chấm từ tệp</h3><p>CSV/TXT tự chia theo Phần;Câu;Đáp án. Mẫu CSV thay đổi theo cấu trúc đã chọn. PDF có chữ được đọc thử; ô không chắc để trống, không đoán khóa từ ảnh.</p><label>Tệp khóa chấm CSV hoặc TXT<input type="file" accept=".csv,.txt,text/csv,text/plain" onChange={e=>{const f=e.target.files?.[0];if(f){if(f.size>1048576)setMessage('Chọn tệp tối đa 1 MB.');else {const request=++generation.current,captured=signature;void f.text().then(text=>read(text,request,captured)).catch(()=>{if(request===generation.current&&captured===context.current)setMessage('Chưa đọc được tệp.');});}}e.target.value='';}}/></label><button type="button" onClick={()=>{const url=URL.createObjectURL(new Blob(['\uFEFF'+(layout?layoutKeyTemplate(layout):keyTemplate())],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='mau-dap-an-mtm.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}}>Tải mẫu CSV đáp án</button>
 <p>Phần dùng số 1, 2, 3… hoặc I, II, III… theo đúng thứ tự. Câu chọn: A/B/C/D · Đ/S: ĐSĐS · Ngắn: theo định dạng đã chọn. Dấu chấm phẩy ngăn cột; dấu phẩy thập phân giữ nguyên.</p>
 <details><summary>Dán bảng CSV / văn bản khóa</summary><label>Nội dung khóa chấm<textarea rows={5} value={paste} onChange={e=>setPaste(e.target.value)}/></label><button type="button" onClick={()=>{generation.current++;read(paste);}}>Nhận diện bảng đã dán</button></details><p role="status">{message}</p>
 {suggestion&&<><ul>{suggestion.messages.map(m=><li key={m}>{m}</li>)}</ul><div className="ep-table-wrap"><table className="ep-score-table"><thead><tr><th>Phần</th><th>Câu</th><th>Đáp án nhận diện</th></tr></thead><tbody>{displayRows.map(r=>{const value=r.kind==='mc'?suggestion.mc[r.kindIndex]:r.kind==='short'?suggestion.short[r.kindIndex]:suggestion.tf[r.kindIndex]?.every(Boolean)?suggestion.tf[r.kindIndex].map(a=>a==='D'?'Đ':'S').join(''):'';return <tr key={r.index}><td>{r.label}</td><td>{r.number}</td><td>{value||'Chưa nhận diện'}</td></tr>;})}</tbody></table></div><button type="button" disabled={!suggestion.matched||suggestion.signature!==signature} onClick={()=>{if(suggestion.signature!==context.current)return;generation.current++;onApply(suggestion);setMessage('Đã điền theo bảng. Các ô không nhận diện để trống; đối chiếu và xác nhận lại.');}}>Áp dụng bảng vào các ô đáp án</button><p>Thay khóa đang nhập; giữ PDF và các bản đã đăng.</p></>}
 </section>;
}
