import type {ExamSection} from '../exams/flexible-profile';
import {canonicalNumeric} from '../exams/assessment';
export type FlexibleFields={layout?:ExamSection[];pointMode?:'auto'|'manual'|'preset';points?:number[];tfScoring?:'thpt'|'equal'|'all';shortMode?:'numeric'|'rational'|'exact';preset?:string};
export const LEGACY_LAYOUT:ExamSection[]=[{label:'I · Trắc nghiệm',kind:'mc',count:12},{label:'II · Đúng/sai',kind:'tf',count:4},{label:'III · Trả lời ngắn',kind:'short',count:6}];
export const PRESETS=[
 {id:'thpt',label:'Tốt nghiệp THPT môn Toán · 12 + 4 + 6',minutes:90,layout:LEGACY_LAYOUT,tf:'thpt' as const,short:'numeric' as const,points:[...Array(12).fill(250),...Array(4).fill(1000),...Array(6).fill(500)],note:'12 câu chọn 0,25 điểm; 4 câu Đ/S theo 0–0,1–0,25–0,5–1 điểm; 6 câu ngắn 0,5 điểm. Tổng 10. 90 phút.',url:'https://vqa.moet.gov.vn/vi/news/thong-bao/cau-truc-dinh-dang-de-thi-tot-nghiep-thpt-tu-nam-2025-74.html'},
 {id:'mc50',label:'50 câu trắc nghiệm × 0,2 điểm',minutes:90,layout:[{label:'I · Trắc nghiệm',kind:'mc' as const,count:50}],note:'50 câu chọn A/B/C/D, mỗi câu 0,2 điểm. Tổng 10.'},
 {id:'mc-tf',label:'Trắc nghiệm + Đúng/Sai',minutes:90,layout:LEGACY_LAYOUT.slice(0,2),note:'Tự sửa số câu từng phần và cách chấm Đ/S theo đề nguồn.'},
 {id:'mc-short',label:'Trắc nghiệm + Trả lời ngắn',minutes:90,layout:[LEGACY_LAYOUT[0],{...LEGACY_LAYOUT[2],label:'II · Trả lời ngắn'}],note:'Tự sửa số câu và phân bổ điểm.'},
 {id:'tf-short',label:'Đúng/Sai + Trả lời ngắn',minutes:90,layout:[{...LEGACY_LAYOUT[1],label:'I · Đúng/sai'},{...LEGACY_LAYOUT[2],label:'II · Trả lời ngắn'}],note:'Tự sửa số câu; mỗi câu Đ/S gồm 4 ý.'},
 {id:'hsa-math',label:'HSA · Toán 50 câu (35 chọn + 15 điền)',minutes:75,layout:[{label:'Toán · Chọn đáp án',kind:'mc' as const,count:35},{label:'Toán · Điền đáp án',kind:'short' as const,count:15}],short:'rational' as const,note:'HSA 2026: Toán 50 câu/75 phút; toàn bài 150 câu/195 phút. Điền số nguyên hoặc phân số tối giản. Đây là luyện tập MTM thang 10, không phải điểm HSA chính thức.',url:'https://www.hsa.edu.vn/huong-dan/dang-thuc-bai-thi'},
 {id:'tsa-math',label:'TSA · Tư duy Toán 40 câu',minutes:60,layout:[{label:'Tư duy Toán · Chọn đáp án',kind:'mc' as const,count:40}],tf:'all' as const,short:'exact' as const,note:'TSA: Toán 40 câu/60 phút, Đọc hiểu 20/30, Khoa học 40/60; toàn bài 100/150. Nguồn không ấn định số câu từng dạng. Thay loại/số câu theo đúng PDF. Mẫu này mới hỗ trợ chọn một, Đ/S và điền; câu nhiều đáp án/kéo thả cần cấu trúc riêng. Điểm luyện MTM không phải điểm IRT TSA.',url:'https://ts.hust.edu.vn/vi/tin-tuc/gioi-thieu-ve-ky-thi-danh-gia-tu-duy-tsa'},
 {id:'custom',label:'Tự chọn cấu trúc và điểm',minutes:90,layout:LEGACY_LAYOUT,note:'Tối đa 12 phần và 300 câu. Mỗi phần có loại và số câu riêng, giữ đúng thứ tự PDF.'}
];
export function validLayout(layout:unknown):layout is ExamSection[]{return Array.isArray(layout)&&layout.length>=1&&layout.length<=12&&layout.every(s=>s&&typeof s.label==='string'&&s.label.trim()&&s.label.length<=100&&['mc','tf','short'].includes(s.kind)&&Number.isInteger(s.count)&&s.count>=1&&s.count<=300)&&layout.reduce((n,s)=>n+s.count,0)<=300;}
/** Deterministic largest-remainder division in 0.001-point units. No hidden rescaling. */
export function autoPoints(count:number){if(!Number.isInteger(count)||count<1||count>300)throw Error('Số câu từ 1 đến 300.');const base=Math.floor(10000/count),remainder=10000%count;return Array.from({length:count},(_,i)=>base+(i<remainder?1:0));}
export function pointsFor(d:FlexibleFields){const count=d.layout?.reduce((n,s)=>n+s.count,0)??22;return d.pointMode==='auto'?autoPoints(count):d.points??[];}
export function tfSchedule(max:number,policy:FlexibleFields['tfScoring']){return (policy==='all'?[0,0,0,0,max]:policy==='thpt'?[0,Math.round(max*.1),Math.round(max*.25),Math.round(max*.5),max]:[0,Math.round(max/4),Math.round(max/2),Math.round(max*3/4),max]) as [number,number,number,number,number];}
export function pointInput(value:string){const n=canonicalNumeric(value);if(n===null||n.startsWith('-')||(n.split('.')[1]?.length??0)>3)return 0;return Math.round(Number(n)*1000);}
export function layoutRows(layout:ExamSection[]){let index=0;const kindIndex={mc:0,tf:0,short:0};return layout.flatMap((s,part)=>Array.from({length:s.count},(_,number)=>({part:part+1,label:s.label,number:number+1,kind:s.kind,index:index++,kindIndex:kindIndex[s.kind]++})));}
