import {useEffect,useState,useRef} from 'react';
import type {AdminDraft} from './model';
import {LEGACY_LAYOUT,PRESETS,validLayout,layoutRows,pointsFor,tfSchedule,pointInput} from './layout';
import type {ExamSection} from '../exams/flexible-profile';
import ExamConfirm from '../exams/ExamConfirm';
const names={mc:'Trắc nghiệm A/B/C/D',tf:'Đúng/Sai (4 ý)',short:'Trả lời ngắn'};
function ManualPointInput({value,onChange}:{value:number;onChange:(units:number)=>void}){const [raw,setRaw]=useState(String(value/1000)),editing=useRef(false);useEffect(()=>{if(!editing.current)setRaw(String(value/1000));},[value]);const units=pointInput(raw),valid=units>0&&units<=10000;return <><input type="text" inputMode="decimal" value={raw} aria-invalid={!valid} onFocus={()=>{editing.current=true;}} onChange={e=>{setRaw(e.target.value);const n=pointInput(e.target.value);onChange(n>0&&n<=10000?n:0);}} onBlur={()=>{editing.current=false;}}/>{!valid&&<small>Nhập điểm dương đến 3 chữ số thập phân, tối đa 10.</small>}</>;}
export default function LayoutEditor({draft,onChange}:{draft:AdminDraft;onChange:(patch:Partial<AdminDraft>)=>void}){
 const [layout,setLayout]=useState<ExamSection[]>(draft.layout??LEGACY_LAYOUT),[pending,setPending]=useState<(()=>void)|null>(null),[error,setError]=useState('');
 useEffect(()=>{setLayout(draft.layout??LEGACY_LAYOUT);},[draft.layout]);
 const points=draft.layout?pointsFor(draft):[...Array(12).fill(250),...Array(4).fill(1000),...Array(6).fill(500)],rows=layoutRows(draft.layout??LEGACY_LAYOUT),total=points.reduce((n,p)=>n+p,0),preset=PRESETS.find(p=>p.id===draft.preset);
 function apply(next:ExamSection[],id='custom'){if(!validLayout(next)){setError('Mỗi phần cần 1–300 câu, tổng tối đa 300 câu và 12 phần.');return;}const chosen=PRESETS.find(p=>p.id===id),r=layoutRows(next),count=(kind:string)=>r.filter(q=>q.kind===kind).length;setPending(()=>()=>{onChange({layout:next.map(s=>({...s})),preset:id,pointMode:chosen?.points?'preset':'auto',points:chosen?.points?[...chosen.points]:undefined,tfScoring:chosen?.tf??'equal',shortMode:chosen?.short??'numeric',durationMinutes:chosen?.minutes??draft.durationMinutes,mc:Array(count('mc')).fill(''),tf:Array.from({length:count('tf')},()=>Array(4).fill('')),short:Array(count('short')).fill(''),solutions:Array(r.length).fill(''),keyReviewed:false,solutionsComplete:false});setError('');});}
 return <fieldset><legend>Cấu trúc và thang điểm</legend><label>Mẫu đề<select value={draft.preset??'legacy'} onChange={e=>{const p=PRESETS.find(p=>p.id===e.target.value);if(p)apply(p.layout,p.id);}}><option value="legacy">Cấu trúc cũ · 12 + 4 + 6</option>{PRESETS.map(p=><option key={p.id} value={p.id}>{p.label}</option>)}</select></label>{preset&&<p>{preset.note} {preset.url&&<a href={preset.url} target="_blank" rel="noopener noreferrer">Nguồn cấu trúc</a>}</p>}
 <p>Chọn mẫu và xác nhận đổi cấu trúc. Nếu tự sửa số câu, loại câu từng phần thì bấm “Áp dụng cấu trúc đã sửa” rồi xác nhận. Tải PDF không tự đổi số câu; cấu trúc cần khớp với đề trong PDF. Ví dụ: 50 câu trắc nghiệm, tự chia tổng 10 thì mỗi câu được 0,2 điểm.</p>
 <p>Đổi cấu trúc sẽ xóa đáp án đúng và lời giải đang nhập sau khi xác nhận; giữ PDF, đề đã đăng và lịch sử. Sửa các loại câu theo đúng thứ tự trong PDF.</p>
 <div className="ma-layout-parts">{layout.map((s,i)=><fieldset key={i}><legend>Phần {i+1}</legend><label>Tên phần {i+1}<input maxLength={100} value={s.label} onChange={e=>setLayout(a=>a.map((x,j)=>j===i?{...x,label:e.target.value}:x))}/></label><label>Loại câu phần {i+1}<select value={s.kind} onChange={e=>setLayout(a=>a.map((x,j)=>j===i?{...x,kind:e.target.value as ExamSection['kind']}:x))}>{Object.entries(names).map(([k,n])=><option key={k} value={k}>{n}</option>)}</select></label><label>Số câu phần {i+1}<input type="number" min={1} max={300} value={s.count} onChange={e=>setLayout(a=>a.map((x,j)=>j===i?{...x,count:Number(e.target.value)}:x))}/></label><button type="button" disabled={layout.length===1} onClick={()=>setLayout(a=>a.filter((_,j)=>j!==i))}>Bỏ phần {i+1}</button></fieldset>)}</div>
 <div className="ma-toolbar"><button type="button" disabled={layout.length>=12} onClick={()=>setLayout(a=>[...a,{label:`Phần ${a.length+1}`,kind:'mc',count:1}])}>Thêm phần</button><button type="button" onClick={()=>apply(layout)}>Áp dụng cấu trúc đã sửa</button></div>{error&&<p role="alert">{error}</p>}
 {draft.layout?<><label>Cách chia điểm<select value={draft.pointMode} onChange={e=>onChange({pointMode:e.target.value as AdminDraft['pointMode'],points:[...points],keyReviewed:false})}><option value="auto">Tự chia tổng 10 theo số câu</option><option value="manual">Nhập điểm từng câu</option>{draft.pointMode==='preset'&&<option value="preset">Điểm theo mẫu đã chọn</option>}</select></label><label>Chấm câu Đúng/Sai<select value={draft.tfScoring} onChange={e=>onChange({tfScoring:e.target.value as AdminDraft['tfScoring'],keyReviewed:false})}><option value="equal">Chia theo số ý đúng: 0, ¼, ½, ¾, toàn bộ</option><option value="thpt">Tỉ lệ THPT: 0, 10%, 25%, 50%, 100%</option><option value="all">Chỉ có điểm khi đúng cả 4 ý</option></select></label><label>Định dạng trả lời ngắn<select value={draft.shortMode} onChange={e=>onChange({shortMode:e.target.value as AdminDraft['shortMode'],keyReviewed:false})}><option value="numeric">Số thập phân (phẩy hoặc chấm)</option><option value="rational">Số hoặc phân số (HSA)</option><option value="exact">Văn bản chính xác (phân biệt hoa/thường)</option></select></label></>:<p>Mẫu cũ: I: 3 điểm · II: 4 điểm · III: 3 điểm.</p>}
 <p role="status"><strong>{rows.length} câu · Tổng {(total/1000).toLocaleString('vi-VN',{maximumFractionDigits:3})}/10 điểm</strong></p>{draft.pointMode==='auto'&&<p>Chia mỗi câu bằng nhau tới 0,001 điểm; phần dư được cộng 0,001 vào các câu đầu để tổng đúng 10. Mỗi câu Đ/S được tính là một câu gồm 4 ý.</p>}
 <details><summary>Xem / sửa điểm từng câu</summary><div className="ep-table-wrap"><table className="ep-score-table"><thead><tr><th>Phần · Câu</th><th>Điểm tối đa</th><th>Điểm Đ/S theo 0–4 ý đúng</th></tr></thead><tbody>{rows.map(r=><tr key={r.index}><th scope="row">{r.label} · {r.number}</th><td>{draft.pointMode==='manual'?<label>Điểm câu {r.index+1}<ManualPointInput value={points[r.index]??0} onChange={units=>onChange({points:points.map((p,j)=>j===r.index?units:p),keyReviewed:false})}/></label>:((points[r.index]??0)/1000).toLocaleString('vi-VN',{maximumFractionDigits:3})}</td><td>{r.kind==='tf'?tfSchedule(points[r.index]??0,draft.tfScoring??'thpt').map(p=>(p/1000).toLocaleString('vi-VN',{maximumFractionDigits:3})).join(' / '):'—'}</td></tr>)}</tbody></table></div></details>
 {pending&&<ExamConfirm title="Đổi cấu trúc đề?" message="Khóa và lời giải đang nhập sẽ được xóa để tránh gán nhầm câu. PDF, thông tin đề, phiên bản đã đăng và lịch sử cũ vẫn được giữ. Nếu muốn giữ khóa hiện tại, bấm Hủy và lưu bản nháp trước." confirmLabel="Đổi cấu trúc" onCancel={()=>setPending(null)} onConfirm={()=>{const run=pending;setPending(null);run();}}/>}
 </fieldset>;
}
