import React,{useEffect,useRef,useState} from 'react';
import type {PdfAsset} from './model';
import {sha256} from './backend';
import {getDocument,GlobalWorkerOptions,AnnotationMode,type PDFDocumentProxy} from 'pdfjs-dist';
import workerUrl from 'pdfjs-dist/build/pdf.worker.min.mjs?url';
GlobalWorkerOptions.workerSrc=workerUrl;
export default function PdfInput({label,onFile,onStart,onEnd,onText}:{label:string;onFile:(file:File,info:Omit<PdfAsset,'path'>)=>Promise<void>;onStart?:()=>boolean;onEnd?:()=>void;onText?:(text:string)=>void}){
 const [doc,setDoc]=useState<PDFDocumentProxy|null>(null),[page,setPage]=useState(1),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);const host=useRef<HTMLDivElement>(null),sequence=useRef(0),taskRef=useRef<ReturnType<typeof getDocument>|null>(null);
 useEffect(()=>()=>{sequence.current++;void taskRef.current?.destroy();},[]);
 useEffect(()=>{if(!doc||!host.current)return;let active=true;let render:ReturnType<Awaited<ReturnType<PDFDocumentProxy['getPage']>>['render']>|undefined;void(async()=>{try{const p=await doc.getPage(page);if(!active)return;const width=Math.max(240,Math.min(800,host.current!.clientWidth-16)),vp=p.getViewport({scale:width/p.getViewport({scale:1}).width});const canvas=document.createElement('canvas');canvas.width=Math.ceil(vp.width);canvas.height=Math.ceil(vp.height);canvas.setAttribute('role','img');canvas.setAttribute('aria-label',`${label}, trang ${page}`);host.current?.replaceChildren(canvas);render=p.render({canvas,viewport:vp,annotationMode:AnnotationMode.DISABLE});await render.promise;}catch{if(active)setMessage('Chưa vẽ được trang PDF. Chọn lại tệp để kiểm tra.');}})();return()=>{active=false;render?.cancel();};},[doc,page,label]);
 async function choose(file:File){if(onStart&&!onStart()){setMessage('Một thao tác khác đang chạy. Chờ xong rồi chọn lại PDF.');return;}const token=++sequence.current;setBusy(true);setMessage('Đang kiểm tra PDF…');setDoc(null);setPage(1);void taskRef.current?.destroy();try{if(!file.name.toLowerCase().endsWith('.pdf')||file.size<8||file.size>15*1024*1024)throw Error('Chọn PDF từ 8 byte đến 15 MB.');const bytes=await file.arrayBuffer();if(new TextDecoder().decode(bytes.slice(0,5))!=='%PDF-')throw Error('Tệp không có cấu trúc PDF.');const hash=await sha256(bytes);const task=getDocument({data:new Uint8Array(bytes.slice(0)),enableXfa:false,stopAtErrors:true,maxImageSize:16000000});taskRef.current=task;const pdf=await task.promise;if(token!==sequence.current){void task.destroy();return;}if(pdf.numPages<1||pdf.numPages>200||await pdf.getJSActions())throw Error('PDF quá 200 trang hoặc chứa mã JavaScript.');setDoc(pdf);if(onText){let lines:string[]=[];for(let page=1;page<=pdf.numPages;page++){const content=await(await pdf.getPage(page)).getTextContent();const rows=new Map<number,{x:number,text:string}[]>();for(const item of content.items){if(!("str" in item))continue;const y=Math.round(item.transform[5]/3)*3;const row=rows.get(y)||[];row.push({x:item.transform[4],text:item.str});rows.set(y,row);}for(const y of [...rows.keys()].sort((a,b)=>b-a))lines.push(rows.get(y)!.sort((a,b)=>a.x-b.x).map(i=>i.text).join("\t"));if(lines.join("\n").length>1048576)throw Error("PDF lời giải có quá nhiều chữ để nhận diện khóa. Vẫn có thể nhập khóa thủ công với PDF ngắn hơn.");}onText(lines.join("\n"));}await onFile(file,{sha256:hash,bytes:file.size,totalPages:pdf.numPages,name:file.name});if(token===sequence.current)setMessage(`Đã tải và kiểm cấu trúc: ${file.name} · ${pdf.numPages} trang · ${Math.ceil(file.size/1024)} KB.`);}catch(e){if(token===sequence.current)setMessage(e instanceof Error?e.message:'Chưa kiểm được PDF.');}finally{if(token===sequence.current)setBusy(false);onEnd?.();}}
 return <section className="ma-pdf"><label>{label}<input aria-label={label} type="file" accept="application/pdf,.pdf" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)void choose(f);e.target.value='';}}/></label><p role="status">{message||'Chọn PDF riêng. Bản câu hỏi không được chứa đáp án hoặc lời giải.'}</p>{doc&&<><div className="ma-toolbar"><button type="button" disabled={page===1} onClick={()=>setPage(p=>p-1)}>Trang trước</button><span>Trang {page}/{doc.numPages}</span><button type="button" disabled={page===doc.numPages} onClick={()=>setPage(p=>p+1)}>Trang sau</button></div><div className="ma-pdf-page" ref={host}/></>}</section>;
}
